package com.nsmjsf.web.datamodels;

// Generated Feb 28, 2015 3:31:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CompanyBranch generated by hbm2java
 */
@Entity
@Table(name = "company_branch", catalog = "admin_nsmjsf")
public class CompanyBranch implements java.io.Serializable {

	private Integer companyBranchId;
	private CompanyBranch companyBranch;
	private String companyBranchAddress;
	private String companyBranchPhone;
	private String companyBranchEmail;
	private Set<CompanyBranch> companyBranches = new HashSet<CompanyBranch>(0);

	public CompanyBranch() {
	}

	public CompanyBranch(CompanyBranch companyBranch,
			String companyBranchAddress, String companyBranchPhone,
			String companyBranchEmail) {
		this.companyBranch = companyBranch;
		this.companyBranchAddress = companyBranchAddress;
		this.companyBranchPhone = companyBranchPhone;
		this.companyBranchEmail = companyBranchEmail;
	}

	public CompanyBranch(CompanyBranch companyBranch,
			String companyBranchAddress, String companyBranchPhone,
			String companyBranchEmail, Set<CompanyBranch> companyBranches) {
		this.companyBranch = companyBranch;
		this.companyBranchAddress = companyBranchAddress;
		this.companyBranchPhone = companyBranchPhone;
		this.companyBranchEmail = companyBranchEmail;
		this.companyBranches = companyBranches;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "company_branch_id", unique = true, nullable = false)
	public Integer getCompanyBranchId() {
		return this.companyBranchId;
	}

	public void setCompanyBranchId(Integer companyBranchId) {
		this.companyBranchId = companyBranchId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company_branch_company_id", nullable = false)
	public CompanyBranch getCompanyBranch() {
		return this.companyBranch;
	}

	public void setCompanyBranch(CompanyBranch companyBranch) {
		this.companyBranch = companyBranch;
	}

	@Column(name = "company_branch_address", nullable = false, length = 65535)
	public String getCompanyBranchAddress() {
		return this.companyBranchAddress;
	}

	public void setCompanyBranchAddress(String companyBranchAddress) {
		this.companyBranchAddress = companyBranchAddress;
	}

	@Column(name = "company_branch_phone", nullable = false)
	public String getCompanyBranchPhone() {
		return this.companyBranchPhone;
	}

	public void setCompanyBranchPhone(String companyBranchPhone) {
		this.companyBranchPhone = companyBranchPhone;
	}

	@Column(name = "company_branch_email", nullable = false)
	public String getCompanyBranchEmail() {
		return this.companyBranchEmail;
	}

	public void setCompanyBranchEmail(String companyBranchEmail) {
		this.companyBranchEmail = companyBranchEmail;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "companyBranch")
	public Set<CompanyBranch> getCompanyBranches() {
		return this.companyBranches;
	}

	public void setCompanyBranches(Set<CompanyBranch> companyBranches) {
		this.companyBranches = companyBranches;
	}

}
