package com.nsmjsf.web.datamodels;

// Generated Feb 28, 2015 3:31:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CompanyDetail generated by hbm2java
 */
@Entity
@Table(name = "company_detail", catalog = "admin_nsmjsf")
public class CompanyDetail implements java.io.Serializable {

	private Integer companyDetailId;
	private Post post;
	private String companyDetailLabel;
	private int companyDetailListedShares;
	private int companyDetailPaidUpValue;
	private int companyDetailTotalPaidUpValue;
	private String companyDetailAddress;
	private String companyDetailPhone;
	private String companyDetailEmail;
	private String companyDetailWeb;
	private String companyDetailPob;
	private String companyDetailFax;
	private Date companyDetailOperationDate;
	private Date companyDetailListingDate;
	private String companyDetailRegistarToShare;
	private String companyDetailProfile;
	private Set<Company> companies = new HashSet<Company>(0);

	public CompanyDetail() {
	}

	public CompanyDetail(Post post, String companyDetailLabel,
			int companyDetailListedShares, int companyDetailPaidUpValue,
			int companyDetailTotalPaidUpValue, String companyDetailAddress,
			String companyDetailPhone, String companyDetailRegistarToShare,
			String companyDetailProfile) {
		this.post = post;
		this.companyDetailLabel = companyDetailLabel;
		this.companyDetailListedShares = companyDetailListedShares;
		this.companyDetailPaidUpValue = companyDetailPaidUpValue;
		this.companyDetailTotalPaidUpValue = companyDetailTotalPaidUpValue;
		this.companyDetailAddress = companyDetailAddress;
		this.companyDetailPhone = companyDetailPhone;
		this.companyDetailRegistarToShare = companyDetailRegistarToShare;
		this.companyDetailProfile = companyDetailProfile;
	}

	public CompanyDetail(Post post, String companyDetailLabel,
			int companyDetailListedShares, int companyDetailPaidUpValue,
			int companyDetailTotalPaidUpValue, String companyDetailAddress,
			String companyDetailPhone, String companyDetailEmail,
			String companyDetailWeb, String companyDetailPob,
			String companyDetailFax, Date companyDetailOperationDate,
			Date companyDetailListingDate, String companyDetailRegistarToShare,
			String companyDetailProfile, Set<Company> companies) {
		this.post = post;
		this.companyDetailLabel = companyDetailLabel;
		this.companyDetailListedShares = companyDetailListedShares;
		this.companyDetailPaidUpValue = companyDetailPaidUpValue;
		this.companyDetailTotalPaidUpValue = companyDetailTotalPaidUpValue;
		this.companyDetailAddress = companyDetailAddress;
		this.companyDetailPhone = companyDetailPhone;
		this.companyDetailEmail = companyDetailEmail;
		this.companyDetailWeb = companyDetailWeb;
		this.companyDetailPob = companyDetailPob;
		this.companyDetailFax = companyDetailFax;
		this.companyDetailOperationDate = companyDetailOperationDate;
		this.companyDetailListingDate = companyDetailListingDate;
		this.companyDetailRegistarToShare = companyDetailRegistarToShare;
		this.companyDetailProfile = companyDetailProfile;
		this.companies = companies;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "company_detail_id", unique = true, nullable = false)
	public Integer getCompanyDetailId() {
		return this.companyDetailId;
	}

	public void setCompanyDetailId(Integer companyDetailId) {
		this.companyDetailId = companyDetailId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company_detail_post_id", nullable = false)
	public Post getPost() {
		return this.post;
	}

	public void setPost(Post post) {
		this.post = post;
	}

	@Column(name = "company_detail_label", nullable = false)
	public String getCompanyDetailLabel() {
		return this.companyDetailLabel;
	}

	public void setCompanyDetailLabel(String companyDetailLabel) {
		this.companyDetailLabel = companyDetailLabel;
	}

	@Column(name = "company_detail_listed_shares", nullable = false)
	public int getCompanyDetailListedShares() {
		return this.companyDetailListedShares;
	}

	public void setCompanyDetailListedShares(int companyDetailListedShares) {
		this.companyDetailListedShares = companyDetailListedShares;
	}

	@Column(name = "company_detail_paid_up_value", nullable = false)
	public int getCompanyDetailPaidUpValue() {
		return this.companyDetailPaidUpValue;
	}

	public void setCompanyDetailPaidUpValue(int companyDetailPaidUpValue) {
		this.companyDetailPaidUpValue = companyDetailPaidUpValue;
	}

	@Column(name = "company_detail_total_paid_up_value", nullable = false)
	public int getCompanyDetailTotalPaidUpValue() {
		return this.companyDetailTotalPaidUpValue;
	}

	public void setCompanyDetailTotalPaidUpValue(
			int companyDetailTotalPaidUpValue) {
		this.companyDetailTotalPaidUpValue = companyDetailTotalPaidUpValue;
	}

	@Column(name = "company_detail_address", nullable = false, length = 65535)
	public String getCompanyDetailAddress() {
		return this.companyDetailAddress;
	}

	public void setCompanyDetailAddress(String companyDetailAddress) {
		this.companyDetailAddress = companyDetailAddress;
	}

	@Column(name = "company_detail_phone", nullable = false)
	public String getCompanyDetailPhone() {
		return this.companyDetailPhone;
	}

	public void setCompanyDetailPhone(String companyDetailPhone) {
		this.companyDetailPhone = companyDetailPhone;
	}

	@Column(name = "company_detail_email")
	public String getCompanyDetailEmail() {
		return this.companyDetailEmail;
	}

	public void setCompanyDetailEmail(String companyDetailEmail) {
		this.companyDetailEmail = companyDetailEmail;
	}

	@Column(name = "company_detail_web", length = 65535)
	public String getCompanyDetailWeb() {
		return this.companyDetailWeb;
	}

	public void setCompanyDetailWeb(String companyDetailWeb) {
		this.companyDetailWeb = companyDetailWeb;
	}

	@Column(name = "company_detail_pob")
	public String getCompanyDetailPob() {
		return this.companyDetailPob;
	}

	public void setCompanyDetailPob(String companyDetailPob) {
		this.companyDetailPob = companyDetailPob;
	}

	@Column(name = "company_detail_fax")
	public String getCompanyDetailFax() {
		return this.companyDetailFax;
	}

	public void setCompanyDetailFax(String companyDetailFax) {
		this.companyDetailFax = companyDetailFax;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "company_detail_operation_date", length = 0)
	public Date getCompanyDetailOperationDate() {
		return this.companyDetailOperationDate;
	}

	public void setCompanyDetailOperationDate(Date companyDetailOperationDate) {
		this.companyDetailOperationDate = companyDetailOperationDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "company_detail_listing_date", length = 0)
	public Date getCompanyDetailListingDate() {
		return this.companyDetailListingDate;
	}

	public void setCompanyDetailListingDate(Date companyDetailListingDate) {
		this.companyDetailListingDate = companyDetailListingDate;
	}

	@Column(name = "company_detail_registar_to_share", nullable = false)
	public String getCompanyDetailRegistarToShare() {
		return this.companyDetailRegistarToShare;
	}

	public void setCompanyDetailRegistarToShare(
			String companyDetailRegistarToShare) {
		this.companyDetailRegistarToShare = companyDetailRegistarToShare;
	}

	@Column(name = "company_detail_profile", nullable = false, length = 16777215)
	public String getCompanyDetailProfile() {
		return this.companyDetailProfile;
	}

	public void setCompanyDetailProfile(String companyDetailProfile) {
		this.companyDetailProfile = companyDetailProfile;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "companyDetail")
	public Set<Company> getCompanies() {
		return this.companies;
	}

	public void setCompanies(Set<Company> companies) {
		this.companies = companies;
	}

}
