package com.nsmjsf.web.datamodels;

// Generated Feb 28, 2015 3:31:39 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FinancialHighlight generated by hbm2java
 */
@Entity
@Table(name = "financial_highlight", catalog = "admin_nsmjsf")
public class FinancialHighlight implements java.io.Serializable {

	private Integer financialHighlightId;
	private Company company;
	private Quarter quarter;
	private FiscalYear fiscalYear;
	private int financialHighlightPaidUpCapital;
	private int financialHighlightReserveAndSurplus;
	private int financialHighlightOperatingProfit;
	private int financialHighlightNetProfit;
	private float financialHighlightNonPerformingLoan;
	private float financialHighlightEarningPerShare;
	private float financialHighlightNetWorthPerShare;
	private float financialHighlightCreditDepositRatio;
	private float financialHighlightPriceEarningRatio;
	private float financialHighlightBookValuePerShare;

	public FinancialHighlight() {
	}

	public FinancialHighlight(Company company, Quarter quarter,
			FiscalYear fiscalYear, int financialHighlightPaidUpCapital,
			int financialHighlightReserveAndSurplus,
			int financialHighlightOperatingProfit,
			int financialHighlightNetProfit,
			float financialHighlightNonPerformingLoan,
			float financialHighlightEarningPerShare,
			float financialHighlightNetWorthPerShare,
			float financialHighlightCreditDepositRatio,
			float financialHighlightPriceEarningRatio,
			float financialHighlightBookValuePerShare) {
		this.company = company;
		this.quarter = quarter;
		this.fiscalYear = fiscalYear;
		this.financialHighlightPaidUpCapital = financialHighlightPaidUpCapital;
		this.financialHighlightReserveAndSurplus = financialHighlightReserveAndSurplus;
		this.financialHighlightOperatingProfit = financialHighlightOperatingProfit;
		this.financialHighlightNetProfit = financialHighlightNetProfit;
		this.financialHighlightNonPerformingLoan = financialHighlightNonPerformingLoan;
		this.financialHighlightEarningPerShare = financialHighlightEarningPerShare;
		this.financialHighlightNetWorthPerShare = financialHighlightNetWorthPerShare;
		this.financialHighlightCreditDepositRatio = financialHighlightCreditDepositRatio;
		this.financialHighlightPriceEarningRatio = financialHighlightPriceEarningRatio;
		this.financialHighlightBookValuePerShare = financialHighlightBookValuePerShare;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "financial_highlight_id", unique = true, nullable = false)
	public Integer getFinancialHighlightId() {
		return this.financialHighlightId;
	}

	public void setFinancialHighlightId(Integer financialHighlightId) {
		this.financialHighlightId = financialHighlightId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "financial_highlight_company_id", nullable = false)
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "financial_highlight_quarter_id", nullable = false)
	public Quarter getQuarter() {
		return this.quarter;
	}

	public void setQuarter(Quarter quarter) {
		this.quarter = quarter;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "financial_highlight_fiscal_year_id", nullable = false)
	public FiscalYear getFiscalYear() {
		return this.fiscalYear;
	}

	public void setFiscalYear(FiscalYear fiscalYear) {
		this.fiscalYear = fiscalYear;
	}

	@Column(name = "financial_highlight_paid_up_capital", nullable = false)
	public int getFinancialHighlightPaidUpCapital() {
		return this.financialHighlightPaidUpCapital;
	}

	public void setFinancialHighlightPaidUpCapital(
			int financialHighlightPaidUpCapital) {
		this.financialHighlightPaidUpCapital = financialHighlightPaidUpCapital;
	}

	@Column(name = "financial_highlight_reserve_and_surplus", nullable = false)
	public int getFinancialHighlightReserveAndSurplus() {
		return this.financialHighlightReserveAndSurplus;
	}

	public void setFinancialHighlightReserveAndSurplus(
			int financialHighlightReserveAndSurplus) {
		this.financialHighlightReserveAndSurplus = financialHighlightReserveAndSurplus;
	}

	@Column(name = "financial_highlight_operating_profit", nullable = false)
	public int getFinancialHighlightOperatingProfit() {
		return this.financialHighlightOperatingProfit;
	}

	public void setFinancialHighlightOperatingProfit(
			int financialHighlightOperatingProfit) {
		this.financialHighlightOperatingProfit = financialHighlightOperatingProfit;
	}

	@Column(name = "financial_highlight_net_profit", nullable = false)
	public int getFinancialHighlightNetProfit() {
		return this.financialHighlightNetProfit;
	}

	public void setFinancialHighlightNetProfit(int financialHighlightNetProfit) {
		this.financialHighlightNetProfit = financialHighlightNetProfit;
	}

	@Column(name = "financial_highlight_non_performing_loan", nullable = false, precision = 12, scale = 0)
	public float getFinancialHighlightNonPerformingLoan() {
		return this.financialHighlightNonPerformingLoan;
	}

	public void setFinancialHighlightNonPerformingLoan(
			float financialHighlightNonPerformingLoan) {
		this.financialHighlightNonPerformingLoan = financialHighlightNonPerformingLoan;
	}

	@Column(name = "financial_highlight_earning_per_share", nullable = false, precision = 12, scale = 0)
	public float getFinancialHighlightEarningPerShare() {
		return this.financialHighlightEarningPerShare;
	}

	public void setFinancialHighlightEarningPerShare(
			float financialHighlightEarningPerShare) {
		this.financialHighlightEarningPerShare = financialHighlightEarningPerShare;
	}

	@Column(name = "financial_highlight_net_worth_per_share", nullable = false, precision = 12, scale = 0)
	public float getFinancialHighlightNetWorthPerShare() {
		return this.financialHighlightNetWorthPerShare;
	}

	public void setFinancialHighlightNetWorthPerShare(
			float financialHighlightNetWorthPerShare) {
		this.financialHighlightNetWorthPerShare = financialHighlightNetWorthPerShare;
	}

	@Column(name = "financial_highlight_credit_deposit_ratio", nullable = false, precision = 12, scale = 0)
	public float getFinancialHighlightCreditDepositRatio() {
		return this.financialHighlightCreditDepositRatio;
	}

	public void setFinancialHighlightCreditDepositRatio(
			float financialHighlightCreditDepositRatio) {
		this.financialHighlightCreditDepositRatio = financialHighlightCreditDepositRatio;
	}

	@Column(name = "financial_highlight_price_earning_ratio", nullable = false, precision = 12, scale = 0)
	public float getFinancialHighlightPriceEarningRatio() {
		return this.financialHighlightPriceEarningRatio;
	}

	public void setFinancialHighlightPriceEarningRatio(
			float financialHighlightPriceEarningRatio) {
		this.financialHighlightPriceEarningRatio = financialHighlightPriceEarningRatio;
	}

	@Column(name = "financial_highlight_book_value_per_share", nullable = false, precision = 12, scale = 0)
	public float getFinancialHighlightBookValuePerShare() {
		return this.financialHighlightBookValuePerShare;
	}

	public void setFinancialHighlightBookValuePerShare(
			float financialHighlightBookValuePerShare) {
		this.financialHighlightBookValuePerShare = financialHighlightBookValuePerShare;
	}

}
