package com.nsmjsf.web.datamodels;

// Generated Feb 28, 2015 3:31:39 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ForumThread generated by hbm2java
 */
@Entity
@Table(name = "forum_thread", catalog = "admin_nsmjsf")
public class ForumThread implements java.io.Serializable {

	private Integer forumThreadId;
	private Post post;

	public ForumThread() {
	}

	public ForumThread(Post post) {
		this.post = post;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "forum_thread_id", unique = true, nullable = false)
	public Integer getForumThreadId() {
		return this.forumThreadId;
	}

	public void setForumThreadId(Integer forumThreadId) {
		this.forumThreadId = forumThreadId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "forum_thread_post_id", nullable = false)
	public Post getPost() {
		return this.post;
	}

	public void setPost(Post post) {
		this.post = post;
	}

}
