package com.nsmjsf.web.datamodels;

// Generated Mar 2, 2015 3:36:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MarketIndex generated by hbm2java
 */
@Entity
@Table(name = "market_index", catalog = "admin_nsmjsf")
public class MarketIndex implements java.io.Serializable {

	private Integer marketIndexId;
	private Post post;
	private IndexType indexType;
	private float marketIndexValue;
	private Date marketIndexDate;

	public MarketIndex() {
	}

	public MarketIndex(Post post, IndexType indexType, float marketIndexValue,
			Date marketIndexDate) {
		this.post = post;
		this.indexType = indexType;
		this.marketIndexValue = marketIndexValue;
		this.marketIndexDate = marketIndexDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "market_index_id", unique = true, nullable = false)
	public Integer getMarketIndexId() {
		return this.marketIndexId;
	}

	public void setMarketIndexId(Integer marketIndexId) {
		this.marketIndexId = marketIndexId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "market_index_post_id", nullable = false)
	public Post getPost() {
		return this.post;
	}

	public void setPost(Post post) {
		this.post = post;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "market_index_type_id", nullable = false)
	public IndexType getIndexType() {
		return this.indexType;
	}

	public void setIndexType(IndexType indexType) {
		this.indexType = indexType;
	}

	@Column(name = "market_index_value", nullable = false, precision = 12, scale = 0)
	public float getMarketIndexValue() {
		return this.marketIndexValue;
	}

	public void setMarketIndexValue(float marketIndexValue) {
		this.marketIndexValue = marketIndexValue;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "market_index_date", nullable = false, length = 0)
	public Date getMarketIndexDate() {
		return this.marketIndexDate;
	}

	public void setMarketIndexDate(Date marketIndexDate) {
		this.marketIndexDate = marketIndexDate;
	}

}
