package com.nsmjsf.web.datamodels;

// Generated Feb 28, 2015 3:31:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PostCategory generated by hbm2java
 */
@Entity
@Table(name = "post_category", catalog = "admin_nsmjsf")
public class PostCategory implements java.io.Serializable {

	private Integer postCategoryId;
	private int postCategoryLabel;
	private Set<MapPostCategory> mapPostCategories = new HashSet<MapPostCategory>(
			0);

	public PostCategory() {
	}

	public PostCategory(int postCategoryLabel) {
		this.postCategoryLabel = postCategoryLabel;
	}

	public PostCategory(int postCategoryLabel,
			Set<MapPostCategory> mapPostCategories) {
		this.postCategoryLabel = postCategoryLabel;
		this.mapPostCategories = mapPostCategories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "post_category_id", unique = true, nullable = false)
	public Integer getPostCategoryId() {
		return this.postCategoryId;
	}

	public void setPostCategoryId(Integer postCategoryId) {
		this.postCategoryId = postCategoryId;
	}

	@Column(name = "post_category_label", nullable = false)
	public int getPostCategoryLabel() {
		return this.postCategoryLabel;
	}

	public void setPostCategoryLabel(int postCategoryLabel) {
		this.postCategoryLabel = postCategoryLabel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "postCategory")
	public Set<MapPostCategory> getMapPostCategories() {
		return this.mapPostCategories;
	}

	public void setMapPostCategories(Set<MapPostCategory> mapPostCategories) {
		this.mapPostCategories = mapPostCategories;
	}

}
