package com.nsmjsf.web.datamodels;

// Generated Feb 28, 2015 3:31:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserBullionSales generated by hbm2java
 */
@Entity
@Table(name = "user_bullion_sales", catalog = "admin_nsmjsf")
public class UserBullionSales implements java.io.Serializable {

	private Integer userBullionSalesId;
	private UserBullion userBullion;
	private float userBullionSalesPrice;
	private float userBullionSalesUnitsSold;
	private Date userBullionSalesDate;
	private double userBullionSalesProfitLoss;

	public UserBullionSales() {
	}

	public UserBullionSales(UserBullion userBullion,
			float userBullionSalesPrice, float userBullionSalesUnitsSold,
			Date userBullionSalesDate, double userBullionSalesProfitLoss) {
		this.userBullion = userBullion;
		this.userBullionSalesPrice = userBullionSalesPrice;
		this.userBullionSalesUnitsSold = userBullionSalesUnitsSold;
		this.userBullionSalesDate = userBullionSalesDate;
		this.userBullionSalesProfitLoss = userBullionSalesProfitLoss;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_bullion_sales_id", unique = true, nullable = false)
	public Integer getUserBullionSalesId() {
		return this.userBullionSalesId;
	}

	public void setUserBullionSalesId(Integer userBullionSalesId) {
		this.userBullionSalesId = userBullionSalesId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_bullion_id", nullable = false)
	public UserBullion getUserBullion() {
		return this.userBullion;
	}

	public void setUserBullion(UserBullion userBullion) {
		this.userBullion = userBullion;
	}

	@Column(name = "user_bullion_sales_price", nullable = false, precision = 12, scale = 0)
	public float getUserBullionSalesPrice() {
		return this.userBullionSalesPrice;
	}

	public void setUserBullionSalesPrice(float userBullionSalesPrice) {
		this.userBullionSalesPrice = userBullionSalesPrice;
	}

	@Column(name = "user_bullion_sales_units_sold", nullable = false, precision = 12, scale = 0)
	public float getUserBullionSalesUnitsSold() {
		return this.userBullionSalesUnitsSold;
	}

	public void setUserBullionSalesUnitsSold(float userBullionSalesUnitsSold) {
		this.userBullionSalesUnitsSold = userBullionSalesUnitsSold;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "user_bullion_sales_date", nullable = false, length = 0)
	public Date getUserBullionSalesDate() {
		return this.userBullionSalesDate;
	}

	public void setUserBullionSalesDate(Date userBullionSalesDate) {
		this.userBullionSalesDate = userBullionSalesDate;
	}

	@Column(name = "user_bullion_sales_profit_loss", nullable = false, precision = 22, scale = 0)
	public double getUserBullionSalesProfitLoss() {
		return this.userBullionSalesProfitLoss;
	}

	public void setUserBullionSalesProfitLoss(double userBullionSalesProfitLoss) {
		this.userBullionSalesProfitLoss = userBullionSalesProfitLoss;
	}

}
