package com.nsmjsf.web.datamodels;

// Generated Feb 28, 2015 3:31:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserPortfolio generated by hbm2java
 */
@Entity
@Table(name = "user_portfolio", catalog = "admin_nsmjsf")
public class UserPortfolio implements java.io.Serializable {

	private Integer userPortfolioId;
	private User user;
	private String userPortfolioLabel;
	private Date userPortfolioCreatedDate;
	private Set<UserStock> userStocks = new HashSet<UserStock>(0);
	private Set<UserEnergy> userEnergies = new HashSet<UserEnergy>(0);

	public UserPortfolio() {
	}

	public UserPortfolio(User user, String userPortfolioLabel,
			Date userPortfolioCreatedDate) {
		this.user = user;
		this.userPortfolioLabel = userPortfolioLabel;
		this.userPortfolioCreatedDate = userPortfolioCreatedDate;
	}

	public UserPortfolio(User user, String userPortfolioLabel,
			Date userPortfolioCreatedDate, Set<UserStock> userStocks,
			Set<UserEnergy> userEnergies) {
		this.user = user;
		this.userPortfolioLabel = userPortfolioLabel;
		this.userPortfolioCreatedDate = userPortfolioCreatedDate;
		this.userStocks = userStocks;
		this.userEnergies = userEnergies;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_portfolio_id", unique = true, nullable = false)
	public Integer getUserPortfolioId() {
		return this.userPortfolioId;
	}

	public void setUserPortfolioId(Integer userPortfolioId) {
		this.userPortfolioId = userPortfolioId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_portfolio_user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "user_portfolio_label", nullable = false)
	public String getUserPortfolioLabel() {
		return this.userPortfolioLabel;
	}

	public void setUserPortfolioLabel(String userPortfolioLabel) {
		this.userPortfolioLabel = userPortfolioLabel;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "user_portfolio_created_date", nullable = false, length = 0)
	public Date getUserPortfolioCreatedDate() {
		return this.userPortfolioCreatedDate;
	}

	public void setUserPortfolioCreatedDate(Date userPortfolioCreatedDate) {
		this.userPortfolioCreatedDate = userPortfolioCreatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userPortfolio")
	public Set<UserStock> getUserStocks() {
		return this.userStocks;
	}

	public void setUserStocks(Set<UserStock> userStocks) {
		this.userStocks = userStocks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userPortfolio")
	public Set<UserEnergy> getUserEnergies() {
		return this.userEnergies;
	}

	public void setUserEnergies(Set<UserEnergy> userEnergies) {
		this.userEnergies = userEnergies;
	}

}
