package com.nsmjsf.web.datamodels;

// Generated Mar 2, 2015 3:36:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserStock generated by hbm2java
 */
@Entity
@Table(name = "user_stock", catalog = "admin_nsmjsf")
public class UserStock implements java.io.Serializable {

	private Integer userStockId;
	private UserPortfolio userPortfolio;
	private User user;
	private Company company;
	private String userStockOwnerName;
	private int userStockUnits;
	private float userStockPrice;
	private double userStockTotalAmount;
	private float userStockServiceCharge;
	private Date userStockEntryDate;
	private int userStockUnitsLeft;
	private Set<UserStockSales> userStockSaleses = new HashSet<UserStockSales>(
			0);

	public UserStock() {
	}

	public UserStock(UserPortfolio userPortfolio, User user, Company company,
			int userStockUnits, float userStockPrice,
			double userStockTotalAmount, float userStockServiceCharge,
			Date userStockEntryDate, int userStockUnitsLeft) {
		this.userPortfolio = userPortfolio;
		this.user = user;
		this.company = company;
		this.userStockUnits = userStockUnits;
		this.userStockPrice = userStockPrice;
		this.userStockTotalAmount = userStockTotalAmount;
		this.userStockServiceCharge = userStockServiceCharge;
		this.userStockEntryDate = userStockEntryDate;
		this.userStockUnitsLeft = userStockUnitsLeft;
	}

	public UserStock(UserPortfolio userPortfolio, User user, Company company,
			String userStockOwnerName, int userStockUnits,
			float userStockPrice, double userStockTotalAmount,
			float userStockServiceCharge, Date userStockEntryDate,
			int userStockUnitsLeft, Set<UserStockSales> userStockSaleses) {
		this.userPortfolio = userPortfolio;
		this.user = user;
		this.company = company;
		this.userStockOwnerName = userStockOwnerName;
		this.userStockUnits = userStockUnits;
		this.userStockPrice = userStockPrice;
		this.userStockTotalAmount = userStockTotalAmount;
		this.userStockServiceCharge = userStockServiceCharge;
		this.userStockEntryDate = userStockEntryDate;
		this.userStockUnitsLeft = userStockUnitsLeft;
		this.userStockSaleses = userStockSaleses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_stock_id", unique = true, nullable = false)
	public Integer getUserStockId() {
		return this.userStockId;
	}

	public void setUserStockId(Integer userStockId) {
		this.userStockId = userStockId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_stock_portfolio_id", nullable = false)
	public UserPortfolio getUserPortfolio() {
		return this.userPortfolio;
	}

	public void setUserPortfolio(UserPortfolio userPortfolio) {
		this.userPortfolio = userPortfolio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_stock_user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_stock_company_id", nullable = false)
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@Column(name = "user_stock_owner_name")
	public String getUserStockOwnerName() {
		return this.userStockOwnerName;
	}

	public void setUserStockOwnerName(String userStockOwnerName) {
		this.userStockOwnerName = userStockOwnerName;
	}

	@Column(name = "user_stock_units", nullable = false)
	public int getUserStockUnits() {
		return this.userStockUnits;
	}

	public void setUserStockUnits(int userStockUnits) {
		this.userStockUnits = userStockUnits;
	}

	@Column(name = "user_stock_price", nullable = false, precision = 12, scale = 0)
	public float getUserStockPrice() {
		return this.userStockPrice;
	}

	public void setUserStockPrice(float userStockPrice) {
		this.userStockPrice = userStockPrice;
	}

	@Column(name = "user_stock_total_amount", nullable = false, precision = 22, scale = 0)
	public double getUserStockTotalAmount() {
		return this.userStockTotalAmount;
	}

	public void setUserStockTotalAmount(double userStockTotalAmount) {
		this.userStockTotalAmount = userStockTotalAmount;
	}

	@Column(name = "user_stock_service_charge", nullable = false, precision = 12, scale = 0)
	public float getUserStockServiceCharge() {
		return this.userStockServiceCharge;
	}

	public void setUserStockServiceCharge(float userStockServiceCharge) {
		this.userStockServiceCharge = userStockServiceCharge;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "user_stock_entry_date", nullable = false, length = 0)
	public Date getUserStockEntryDate() {
		return this.userStockEntryDate;
	}

	public void setUserStockEntryDate(Date userStockEntryDate) {
		this.userStockEntryDate = userStockEntryDate;
	}

	@Column(name = "user_stock_units_left", nullable = false)
	public int getUserStockUnitsLeft() {
		return this.userStockUnitsLeft;
	}

	public void setUserStockUnitsLeft(int userStockUnitsLeft) {
		this.userStockUnitsLeft = userStockUnitsLeft;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userStock")
	public Set<UserStockSales> getUserStockSaleses() {
		return this.userStockSaleses;
	}

	public void setUserStockSaleses(Set<UserStockSales> userStockSaleses) {
		this.userStockSaleses = userStockSaleses;
	}

}
