package com.nsmjsf.web.datamodels;

// Generated Mar 14, 2015 9:52:11 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Agm generated by hbm2java
 */
@Entity
@Table(name = "agm", catalog = "admin_nsmjsf")
public class Agm implements java.io.Serializable {

	private Integer agmId;
	private FiscalYear fiscalYear;
	private Company company;
	private Announcement announcement;
	private String agmLabel;
	private String agmNumber;
	private String agmVenue;
	private Date agmBookClosureFrom;
	private Date agmBookClosureTo;
	private String agmType;
	private Date agmDate;
	private String agmAgenda;
	private Float agmBonus;
	private Float agmDividend;

	public Agm() {
	}

	public Agm(FiscalYear fiscalYear, Company company,
			Announcement announcement, String agmLabel, String agmVenue,
			String agmType, Date agmDate) {
		this.fiscalYear = fiscalYear;
		this.company = company;
		this.announcement = announcement;
		this.agmLabel = agmLabel;
		this.agmVenue = agmVenue;
		this.agmType = agmType;
		this.agmDate = agmDate;
	}

	public Agm(FiscalYear fiscalYear, Company company,
			Announcement announcement, String agmLabel, String agmNumber,
			String agmVenue, Date agmBookClosureFrom, Date agmBookClosureTo,
			String agmType, Date agmDate, String agmAgenda, Float agmBonus,
			Float agmDividend) {
		this.fiscalYear = fiscalYear;
		this.company = company;
		this.announcement = announcement;
		this.agmLabel = agmLabel;
		this.agmNumber = agmNumber;
		this.agmVenue = agmVenue;
		this.agmBookClosureFrom = agmBookClosureFrom;
		this.agmBookClosureTo = agmBookClosureTo;
		this.agmType = agmType;
		this.agmDate = agmDate;
		this.agmAgenda = agmAgenda;
		this.agmBonus = agmBonus;
		this.agmDividend = agmDividend;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "agm_id", unique = true, nullable = false)
	public Integer getAgmId() {
		return this.agmId;
	}

	public void setAgmId(Integer agmId) {
		this.agmId = agmId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "agm_fiscal_year_id", nullable = false)
	public FiscalYear getFiscalYear() {
		return this.fiscalYear;
	}

	public void setFiscalYear(FiscalYear fiscalYear) {
		this.fiscalYear = fiscalYear;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "agm_company_id", nullable = false)
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "agm_announcement_id", nullable = false)
	public Announcement getAnnouncement() {
		return this.announcement;
	}

	public void setAnnouncement(Announcement announcement) {
		this.announcement = announcement;
	}

	@Column(name = "agm_label", nullable = false)
	public String getAgmLabel() {
		return this.agmLabel;
	}

	public void setAgmLabel(String agmLabel) {
		this.agmLabel = agmLabel;
	}

	@Column(name = "agm_number")
	public String getAgmNumber() {
		return this.agmNumber;
	}

	public void setAgmNumber(String agmNumber) {
		this.agmNumber = agmNumber;
	}

	@Column(name = "agm_venue", nullable = false)
	public String getAgmVenue() {
		return this.agmVenue;
	}

	public void setAgmVenue(String agmVenue) {
		this.agmVenue = agmVenue;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "agm_book_closure_from", length = 0)
	public Date getAgmBookClosureFrom() {
		return this.agmBookClosureFrom;
	}

	public void setAgmBookClosureFrom(Date agmBookClosureFrom) {
		this.agmBookClosureFrom = agmBookClosureFrom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "agm_book_closure_to", length = 0)
	public Date getAgmBookClosureTo() {
		return this.agmBookClosureTo;
	}

	public void setAgmBookClosureTo(Date agmBookClosureTo) {
		this.agmBookClosureTo = agmBookClosureTo;
	}

	@Column(name = "agm_type", nullable = false)
	public String getAgmType() {
		return this.agmType;
	}

	public void setAgmType(String agmType) {
		this.agmType = agmType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "agm_date", nullable = false, length = 0)
	public Date getAgmDate() {
		return this.agmDate;
	}

	public void setAgmDate(Date agmDate) {
		this.agmDate = agmDate;
	}

	@Column(name = "agm_agenda", length = 65535)
	public String getAgmAgenda() {
		return this.agmAgenda;
	}

	public void setAgmAgenda(String agmAgenda) {
		this.agmAgenda = agmAgenda;
	}

	@Column(name = "agm_bonus", precision = 12, scale = 0)
	public Float getAgmBonus() {
		return this.agmBonus;
	}

	public void setAgmBonus(Float agmBonus) {
		this.agmBonus = agmBonus;
	}

	@Column(name = "agm_dividend", precision = 12, scale = 0)
	public Float getAgmDividend() {
		return this.agmDividend;
	}

	public void setAgmDividend(Float agmDividend) {
		this.agmDividend = agmDividend;
	}

}
