package com.nsmjsf.web.datamodels;

// Generated Feb 28, 2015 11:53:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AllotmentResult generated by hbm2java
 */
@Entity
@Table(name = "allotment_result", catalog = "admin_nsmjsf")
public class AllotmentResult implements java.io.Serializable {

	private Integer allotmentResultId;
	private Company company;
	private Announcement announcement;
	private Post post;
	private Integer allotmentResultApplicationNo;
	private String allotmentResultFirstName;
	private String allotmentResultLastName;
	private Integer allotmentResultApplied;
	private Integer allotmentResultAllotted;
	private Date allotmentResultDate;

	public AllotmentResult() {
	}

	public AllotmentResult(Company company, Announcement announcement, Post post) {
		this.company = company;
		this.announcement = announcement;
		this.post = post;
	}

	public AllotmentResult(Company company, Announcement announcement,
			Post post, Integer allotmentResultApplicationNo,
			String allotmentResultFirstName, String allotmentResultLastName,
			Integer allotmentResultApplied, Integer allotmentResultAllotted,
			Date allotmentResultDate) {
		this.company = company;
		this.announcement = announcement;
		this.post = post;
		this.allotmentResultApplicationNo = allotmentResultApplicationNo;
		this.allotmentResultFirstName = allotmentResultFirstName;
		this.allotmentResultLastName = allotmentResultLastName;
		this.allotmentResultApplied = allotmentResultApplied;
		this.allotmentResultAllotted = allotmentResultAllotted;
		this.allotmentResultDate = allotmentResultDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "allotment_result_id", unique = true, nullable = false)
	public Integer getAllotmentResultId() {
		return this.allotmentResultId;
	}

	public void setAllotmentResultId(Integer allotmentResultId) {
		this.allotmentResultId = allotmentResultId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "allotment_result_company_id", nullable = false)
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "allotment_result_announcement_id", nullable = false)
	public Announcement getAnnouncement() {
		return this.announcement;
	}

	public void setAnnouncement(Announcement announcement) {
		this.announcement = announcement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "allotment_result_post_id", nullable = false)
	public Post getPost() {
		return this.post;
	}

	public void setPost(Post post) {
		this.post = post;
	}

	@Column(name = "allotment_result_application_no")
	public Integer getAllotmentResultApplicationNo() {
		return this.allotmentResultApplicationNo;
	}

	public void setAllotmentResultApplicationNo(
			Integer allotmentResultApplicationNo) {
		this.allotmentResultApplicationNo = allotmentResultApplicationNo;
	}

	@Column(name = "allotment_result_first_name")
	public String getAllotmentResultFirstName() {
		return this.allotmentResultFirstName;
	}

	public void setAllotmentResultFirstName(String allotmentResultFirstName) {
		this.allotmentResultFirstName = allotmentResultFirstName;
	}

	@Column(name = "allotment_result_last_name")
	public String getAllotmentResultLastName() {
		return this.allotmentResultLastName;
	}

	public void setAllotmentResultLastName(String allotmentResultLastName) {
		this.allotmentResultLastName = allotmentResultLastName;
	}

	@Column(name = "allotment_result_applied")
	public Integer getAllotmentResultApplied() {
		return this.allotmentResultApplied;
	}

	public void setAllotmentResultApplied(Integer allotmentResultApplied) {
		this.allotmentResultApplied = allotmentResultApplied;
	}

	@Column(name = "allotment_result_allotted")
	public Integer getAllotmentResultAllotted() {
		return this.allotmentResultAllotted;
	}

	public void setAllotmentResultAllotted(Integer allotmentResultAllotted) {
		this.allotmentResultAllotted = allotmentResultAllotted;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "allotment_result_date", length = 0)
	public Date getAllotmentResultDate() {
		return this.allotmentResultDate;
	}

	public void setAllotmentResultDate(Date allotmentResultDate) {
		this.allotmentResultDate = allotmentResultDate;
	}

}
