package com.nsmjsf.web.datamodels;

// Generated Feb 28, 2015 11:53:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Article generated by hbm2java
 */
@Entity
@Table(name = "article", catalog = "admin_nsmjsf")
public class Article implements java.io.Serializable {

	private Integer articleId;
	private Post post;
	private User user;
	private Date articleDate;
	private String articleLocation;
	private String articleHighlight;
	private boolean articleFlag;

	public Article() {
	}

	public Article(Post post, User user, Date articleDate, boolean articleFlag) {
		this.post = post;
		this.user = user;
		this.articleDate = articleDate;
		this.articleFlag = articleFlag;
	}

	public Article(Post post, User user, Date articleDate,
			String articleLocation, String articleHighlight, boolean articleFlag) {
		this.post = post;
		this.user = user;
		this.articleDate = articleDate;
		this.articleLocation = articleLocation;
		this.articleHighlight = articleHighlight;
		this.articleFlag = articleFlag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "article_id", unique = true, nullable = false)
	public Integer getArticleId() {
		return this.articleId;
	}

	public void setArticleId(Integer articleId) {
		this.articleId = articleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "article_post_id", nullable = false)
	public Post getPost() {
		return this.post;
	}

	public void setPost(Post post) {
		this.post = post;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "article_user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "article_date", nullable = false, length = 0)
	public Date getArticleDate() {
		return this.articleDate;
	}

	public void setArticleDate(Date articleDate) {
		this.articleDate = articleDate;
	}

	@Column(name = "article_location", length = 65535)
	public String getArticleLocation() {
		return this.articleLocation;
	}

	public void setArticleLocation(String articleLocation) {
		this.articleLocation = articleLocation;
	}

	@Column(name = "article_highlight", length = 65535)
	public String getArticleHighlight() {
		return this.articleHighlight;
	}

	public void setArticleHighlight(String articleHighlight) {
		this.articleHighlight = articleHighlight;
	}

	@Column(name = "article_flag", nullable = false)
	public boolean isArticleFlag() {
		return this.articleFlag;
	}

	public void setArticleFlag(boolean articleFlag) {
		this.articleFlag = articleFlag;
	}

}
