package com.nsmjsf.web.datamodels;

// Generated Mar 2, 2015 3:36:21 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Balancesheet generated by hbm2java
 */
@Entity
@Table(name = "balancesheet", catalog = "admin_nsmjsf")
public class Balancesheet implements java.io.Serializable {

	private Integer balancesheetId;
	private FinancialReport financialReport;
	private float balancesheetBalanceWithFinancialInstitution;
	private float balancesheetShareCapital;
	private float balancesheetReserveSurplus;
	private float balancesheetNoncontrollingInterest;
	private float balancesheetDebentureBond;
	private float balancesheetLoansBorrowing;
	private float balancesheetDepositLiability;
	private float balancesheetDomesticCurrency;
	private float balancesheetForeignCurrency;
	private float balancesheetBillsPayable;
	private float balancesheetProposedDividend;
	private float balancesheetIncomeTaxLiability;
	private float balancesheetOtherLiabilities;
	private float balancesheetCashBalance;
	private float balancesheetMoneyAtCallAndShortNotice;
	private float balancesheetInvestments;
	private float balancesheetLoanAdvances;
	private float balancesheetRealEstateLoan;
	private float balancesheetResidentialRealEstateLoan;
	private float balancesheetBusinessComplexAndResidentialApartConstLoan;
	private float balancesheetIncomeGeneratingCommericalComplexLoan;
	private float balancesheetOtherRealEstateLoan;
	private float balancesheetPersonalHomeLoanOfRs10millionOrLess;
	private float balancesheetMarginTypeLoan;
	private float balancesheetTermLoan;
	private float balancesheetOverdrafTrLoanWcLoan;
	private float balancesheetOther;
	private float balancesheetFixedAssets;
	private float balancesheetNonBankingAssets;
	private float balancesheetOtherAssets;
	private float balancesheetTotalLiabilities;
	private float balancesheetTotalAssets;

	public Balancesheet() {
	}

	public Balancesheet(FinancialReport financialReport,
			float balancesheetBalanceWithFinancialInstitution,
			float balancesheetShareCapital, float balancesheetReserveSurplus,
			float balancesheetNoncontrollingInterest,
			float balancesheetDebentureBond, float balancesheetLoansBorrowing,
			float balancesheetDepositLiability,
			float balancesheetDomesticCurrency,
			float balancesheetForeignCurrency, float balancesheetBillsPayable,
			float balancesheetProposedDividend,
			float balancesheetIncomeTaxLiability,
			float balancesheetOtherLiabilities, float balancesheetCashBalance,
			float balancesheetMoneyAtCallAndShortNotice,
			float balancesheetInvestments, float balancesheetLoanAdvances,
			float balancesheetRealEstateLoan,
			float balancesheetResidentialRealEstateLoan,
			float balancesheetBusinessComplexAndResidentialApartConstLoan,
			float balancesheetIncomeGeneratingCommericalComplexLoan,
			float balancesheetOtherRealEstateLoan,
			float balancesheetPersonalHomeLoanOfRs10millionOrLess,
			float balancesheetMarginTypeLoan, float balancesheetTermLoan,
			float balancesheetOverdrafTrLoanWcLoan, float balancesheetOther,
			float balancesheetFixedAssets, float balancesheetNonBankingAssets,
			float balancesheetOtherAssets, float balancesheetTotalLiabilities,
			float balancesheetTotalAssets) {
		this.financialReport = financialReport;
		this.balancesheetBalanceWithFinancialInstitution = balancesheetBalanceWithFinancialInstitution;
		this.balancesheetShareCapital = balancesheetShareCapital;
		this.balancesheetReserveSurplus = balancesheetReserveSurplus;
		this.balancesheetNoncontrollingInterest = balancesheetNoncontrollingInterest;
		this.balancesheetDebentureBond = balancesheetDebentureBond;
		this.balancesheetLoansBorrowing = balancesheetLoansBorrowing;
		this.balancesheetDepositLiability = balancesheetDepositLiability;
		this.balancesheetDomesticCurrency = balancesheetDomesticCurrency;
		this.balancesheetForeignCurrency = balancesheetForeignCurrency;
		this.balancesheetBillsPayable = balancesheetBillsPayable;
		this.balancesheetProposedDividend = balancesheetProposedDividend;
		this.balancesheetIncomeTaxLiability = balancesheetIncomeTaxLiability;
		this.balancesheetOtherLiabilities = balancesheetOtherLiabilities;
		this.balancesheetCashBalance = balancesheetCashBalance;
		this.balancesheetMoneyAtCallAndShortNotice = balancesheetMoneyAtCallAndShortNotice;
		this.balancesheetInvestments = balancesheetInvestments;
		this.balancesheetLoanAdvances = balancesheetLoanAdvances;
		this.balancesheetRealEstateLoan = balancesheetRealEstateLoan;
		this.balancesheetResidentialRealEstateLoan = balancesheetResidentialRealEstateLoan;
		this.balancesheetBusinessComplexAndResidentialApartConstLoan = balancesheetBusinessComplexAndResidentialApartConstLoan;
		this.balancesheetIncomeGeneratingCommericalComplexLoan = balancesheetIncomeGeneratingCommericalComplexLoan;
		this.balancesheetOtherRealEstateLoan = balancesheetOtherRealEstateLoan;
		this.balancesheetPersonalHomeLoanOfRs10millionOrLess = balancesheetPersonalHomeLoanOfRs10millionOrLess;
		this.balancesheetMarginTypeLoan = balancesheetMarginTypeLoan;
		this.balancesheetTermLoan = balancesheetTermLoan;
		this.balancesheetOverdrafTrLoanWcLoan = balancesheetOverdrafTrLoanWcLoan;
		this.balancesheetOther = balancesheetOther;
		this.balancesheetFixedAssets = balancesheetFixedAssets;
		this.balancesheetNonBankingAssets = balancesheetNonBankingAssets;
		this.balancesheetOtherAssets = balancesheetOtherAssets;
		this.balancesheetTotalLiabilities = balancesheetTotalLiabilities;
		this.balancesheetTotalAssets = balancesheetTotalAssets;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "balancesheet_id", unique = true, nullable = false)
	public Integer getBalancesheetId() {
		return this.balancesheetId;
	}

	public void setBalancesheetId(Integer balancesheetId) {
		this.balancesheetId = balancesheetId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "balancesheet_financial_report_id", nullable = false)
	public FinancialReport getFinancialReport() {
		return this.financialReport;
	}

	public void setFinancialReport(FinancialReport financialReport) {
		this.financialReport = financialReport;
	}

	@Column(name = "balancesheet_balance_with_financial_institution", nullable = false, precision = 12, scale = 0)
	public float getBalancesheetBalanceWithFinancialInstitution() {
		return this.balancesheetBalanceWithFinancialInstitution;
	}

	public void setBalancesheetBalanceWithFinancialInstitution(
			float balancesheetBalanceWithFinancialInstitution) {
		this.balancesheetBalanceWithFinancialInstitution = balancesheetBalanceWithFinancialInstitution;
	}

	@Column(name = "balancesheet_share_capital", nullable = false, precision = 12, scale = 0)
	public float getBalancesheetShareCapital() {
		return this.balancesheetShareCapital;
	}

	public void setBalancesheetShareCapital(float balancesheetShareCapital) {
		this.balancesheetShareCapital = balancesheetShareCapital;
	}

	@Column(name = "balancesheet_reserve_surplus", nullable = false, precision = 12, scale = 0)
	public float getBalancesheetReserveSurplus() {
		return this.balancesheetReserveSurplus;
	}

	public void setBalancesheetReserveSurplus(float balancesheetReserveSurplus) {
		this.balancesheetReserveSurplus = balancesheetReserveSurplus;
	}

	@Column(name = "balancesheet_noncontrolling_interest", nullable = false, precision = 12, scale = 0)
	public float getBalancesheetNoncontrollingInterest() {
		return this.balancesheetNoncontrollingInterest;
	}

	public void setBalancesheetNoncontrollingInterest(
			float balancesheetNoncontrollingInterest) {
		this.balancesheetNoncontrollingInterest = balancesheetNoncontrollingInterest;
	}

	@Column(name = "balancesheet_debenture_bond", nullable = false, precision = 12, scale = 0)
	public float getBalancesheetDebentureBond() {
		return this.balancesheetDebentureBond;
	}

	public void setBalancesheetDebentureBond(float balancesheetDebentureBond) {
		this.balancesheetDebentureBond = balancesheetDebentureBond;
	}

	@Column(name = "balancesheet_loans_borrowing", nullable = false, precision = 12, scale = 0)
	public float getBalancesheetLoansBorrowing() {
		return this.balancesheetLoansBorrowing;
	}

	public void setBalancesheetLoansBorrowing(float balancesheetLoansBorrowing) {
		this.balancesheetLoansBorrowing = balancesheetLoansBorrowing;
	}

	@Column(name = "balancesheet_deposit_liability", nullable = false, precision = 12, scale = 0)
	public float getBalancesheetDepositLiability() {
		return this.balancesheetDepositLiability;
	}

	public void setBalancesheetDepositLiability(
			float balancesheetDepositLiability) {
		this.balancesheetDepositLiability = balancesheetDepositLiability;
	}

	@Column(name = "balancesheet_domestic_currency", nullable = false, precision = 12, scale = 0)
	public float getBalancesheetDomesticCurrency() {
		return this.balancesheetDomesticCurrency;
	}

	public void setBalancesheetDomesticCurrency(
			float balancesheetDomesticCurrency) {
		this.balancesheetDomesticCurrency = balancesheetDomesticCurrency;
	}

	@Column(name = "balancesheet_foreign_currency", nullable = false, precision = 12, scale = 0)
	public float getBalancesheetForeignCurrency() {
		return this.balancesheetForeignCurrency;
	}

	public void setBalancesheetForeignCurrency(float balancesheetForeignCurrency) {
		this.balancesheetForeignCurrency = balancesheetForeignCurrency;
	}

	@Column(name = "balancesheet_bills_payable", nullable = false, precision = 12, scale = 0)
	public float getBalancesheetBillsPayable() {
		return this.balancesheetBillsPayable;
	}

	public void setBalancesheetBillsPayable(float balancesheetBillsPayable) {
		this.balancesheetBillsPayable = balancesheetBillsPayable;
	}

	@Column(name = "balancesheet_proposed_dividend", nullable = false, precision = 12, scale = 0)
	public float getBalancesheetProposedDividend() {
		return this.balancesheetProposedDividend;
	}

	public void setBalancesheetProposedDividend(
			float balancesheetProposedDividend) {
		this.balancesheetProposedDividend = balancesheetProposedDividend;
	}

	@Column(name = "balancesheet_income_tax_liability", nullable = false, precision = 12, scale = 0)
	public float getBalancesheetIncomeTaxLiability() {
		return this.balancesheetIncomeTaxLiability;
	}

	public void setBalancesheetIncomeTaxLiability(
			float balancesheetIncomeTaxLiability) {
		this.balancesheetIncomeTaxLiability = balancesheetIncomeTaxLiability;
	}

	@Column(name = "balancesheet_other_liabilities", nullable = false, precision = 12, scale = 0)
	public float getBalancesheetOtherLiabilities() {
		return this.balancesheetOtherLiabilities;
	}

	public void setBalancesheetOtherLiabilities(
			float balancesheetOtherLiabilities) {
		this.balancesheetOtherLiabilities = balancesheetOtherLiabilities;
	}

	@Column(name = "balancesheet_cash_balance", nullable = false, precision = 12, scale = 0)
	public float getBalancesheetCashBalance() {
		return this.balancesheetCashBalance;
	}

	public void setBalancesheetCashBalance(float balancesheetCashBalance) {
		this.balancesheetCashBalance = balancesheetCashBalance;
	}

	@Column(name = "balancesheet_money_at_call_and_short_notice", nullable = false, precision = 12, scale = 0)
	public float getBalancesheetMoneyAtCallAndShortNotice() {
		return this.balancesheetMoneyAtCallAndShortNotice;
	}

	public void setBalancesheetMoneyAtCallAndShortNotice(
			float balancesheetMoneyAtCallAndShortNotice) {
		this.balancesheetMoneyAtCallAndShortNotice = balancesheetMoneyAtCallAndShortNotice;
	}

	@Column(name = "balancesheet_investments", nullable = false, precision = 12, scale = 0)
	public float getBalancesheetInvestments() {
		return this.balancesheetInvestments;
	}

	public void setBalancesheetInvestments(float balancesheetInvestments) {
		this.balancesheetInvestments = balancesheetInvestments;
	}

	@Column(name = "balancesheet_loan_advances", nullable = false, precision = 12, scale = 0)
	public float getBalancesheetLoanAdvances() {
		return this.balancesheetLoanAdvances;
	}

	public void setBalancesheetLoanAdvances(float balancesheetLoanAdvances) {
		this.balancesheetLoanAdvances = balancesheetLoanAdvances;
	}

	@Column(name = "balancesheet_real_estate_loan", nullable = false, precision = 12, scale = 0)
	public float getBalancesheetRealEstateLoan() {
		return this.balancesheetRealEstateLoan;
	}

	public void setBalancesheetRealEstateLoan(float balancesheetRealEstateLoan) {
		this.balancesheetRealEstateLoan = balancesheetRealEstateLoan;
	}

	@Column(name = "balancesheet_residential_real_estate_loan", nullable = false, precision = 12, scale = 0)
	public float getBalancesheetResidentialRealEstateLoan() {
		return this.balancesheetResidentialRealEstateLoan;
	}

	public void setBalancesheetResidentialRealEstateLoan(
			float balancesheetResidentialRealEstateLoan) {
		this.balancesheetResidentialRealEstateLoan = balancesheetResidentialRealEstateLoan;
	}

	@Column(name = "balancesheet_business_complex_and_residential_apart_const_loan", nullable = false, precision = 12, scale = 0)
	public float getBalancesheetBusinessComplexAndResidentialApartConstLoan() {
		return this.balancesheetBusinessComplexAndResidentialApartConstLoan;
	}

	public void setBalancesheetBusinessComplexAndResidentialApartConstLoan(
			float balancesheetBusinessComplexAndResidentialApartConstLoan) {
		this.balancesheetBusinessComplexAndResidentialApartConstLoan = balancesheetBusinessComplexAndResidentialApartConstLoan;
	}

	@Column(name = "balancesheet_income_generating_commerical_complex_loan", nullable = false, precision = 12, scale = 0)
	public float getBalancesheetIncomeGeneratingCommericalComplexLoan() {
		return this.balancesheetIncomeGeneratingCommericalComplexLoan;
	}

	public void setBalancesheetIncomeGeneratingCommericalComplexLoan(
			float balancesheetIncomeGeneratingCommericalComplexLoan) {
		this.balancesheetIncomeGeneratingCommericalComplexLoan = balancesheetIncomeGeneratingCommericalComplexLoan;
	}

	@Column(name = "balancesheet_other_real_estate_loan", nullable = false, precision = 12, scale = 0)
	public float getBalancesheetOtherRealEstateLoan() {
		return this.balancesheetOtherRealEstateLoan;
	}

	public void setBalancesheetOtherRealEstateLoan(
			float balancesheetOtherRealEstateLoan) {
		this.balancesheetOtherRealEstateLoan = balancesheetOtherRealEstateLoan;
	}

	@Column(name = "balancesheet_personal_home_loan_of_rs_10million_or_less", nullable = false, precision = 12, scale = 0)
	public float getBalancesheetPersonalHomeLoanOfRs10millionOrLess() {
		return this.balancesheetPersonalHomeLoanOfRs10millionOrLess;
	}

	public void setBalancesheetPersonalHomeLoanOfRs10millionOrLess(
			float balancesheetPersonalHomeLoanOfRs10millionOrLess) {
		this.balancesheetPersonalHomeLoanOfRs10millionOrLess = balancesheetPersonalHomeLoanOfRs10millionOrLess;
	}

	@Column(name = "balancesheet_margin_type_loan", nullable = false, precision = 12, scale = 0)
	public float getBalancesheetMarginTypeLoan() {
		return this.balancesheetMarginTypeLoan;
	}

	public void setBalancesheetMarginTypeLoan(float balancesheetMarginTypeLoan) {
		this.balancesheetMarginTypeLoan = balancesheetMarginTypeLoan;
	}

	@Column(name = "balancesheet_term_loan", nullable = false, precision = 12, scale = 0)
	public float getBalancesheetTermLoan() {
		return this.balancesheetTermLoan;
	}

	public void setBalancesheetTermLoan(float balancesheetTermLoan) {
		this.balancesheetTermLoan = balancesheetTermLoan;
	}

	@Column(name = "balancesheet_overdraf_tr_loan_wc_loan", nullable = false, precision = 12, scale = 0)
	public float getBalancesheetOverdrafTrLoanWcLoan() {
		return this.balancesheetOverdrafTrLoanWcLoan;
	}

	public void setBalancesheetOverdrafTrLoanWcLoan(
			float balancesheetOverdrafTrLoanWcLoan) {
		this.balancesheetOverdrafTrLoanWcLoan = balancesheetOverdrafTrLoanWcLoan;
	}

	@Column(name = "balancesheet_other", nullable = false, precision = 12, scale = 0)
	public float getBalancesheetOther() {
		return this.balancesheetOther;
	}

	public void setBalancesheetOther(float balancesheetOther) {
		this.balancesheetOther = balancesheetOther;
	}

	@Column(name = "balancesheet_fixed_assets", nullable = false, precision = 12, scale = 0)
	public float getBalancesheetFixedAssets() {
		return this.balancesheetFixedAssets;
	}

	public void setBalancesheetFixedAssets(float balancesheetFixedAssets) {
		this.balancesheetFixedAssets = balancesheetFixedAssets;
	}

	@Column(name = "balancesheet_non_banking_assets", nullable = false, precision = 12, scale = 0)
	public float getBalancesheetNonBankingAssets() {
		return this.balancesheetNonBankingAssets;
	}

	public void setBalancesheetNonBankingAssets(
			float balancesheetNonBankingAssets) {
		this.balancesheetNonBankingAssets = balancesheetNonBankingAssets;
	}

	@Column(name = "balancesheet_other_assets", nullable = false, precision = 12, scale = 0)
	public float getBalancesheetOtherAssets() {
		return this.balancesheetOtherAssets;
	}

	public void setBalancesheetOtherAssets(float balancesheetOtherAssets) {
		this.balancesheetOtherAssets = balancesheetOtherAssets;
	}

	@Column(name = "balancesheet_total_liabilities", nullable = false, precision = 12, scale = 0)
	public float getBalancesheetTotalLiabilities() {
		return this.balancesheetTotalLiabilities;
	}

	public void setBalancesheetTotalLiabilities(
			float balancesheetTotalLiabilities) {
		this.balancesheetTotalLiabilities = balancesheetTotalLiabilities;
	}

	@Column(name = "balancesheet_total_assets", nullable = false, precision = 12, scale = 0)
	public float getBalancesheetTotalAssets() {
		return this.balancesheetTotalAssets;
	}

	public void setBalancesheetTotalAssets(float balancesheetTotalAssets) {
		this.balancesheetTotalAssets = balancesheetTotalAssets;
	}

}
