package com.nsmjsf.web.datamodels;

// Generated Feb 28, 2015 11:53:30 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Bod generated by hbm2java
 */
@Entity
@Table(name = "bod", catalog = "admin_nsmjsf")
public class Bod implements java.io.Serializable {

	private Integer bodId;
	private FiscalYear fiscalYear;
	private BodType bodType;
	private Company company;
	private String bodName;
	private String bodType_1;
	private String bodPost;
	private String bodPhoto;
	private String bodBio;

	public Bod() {
	}

	public Bod(FiscalYear fiscalYear, BodType bodType, Company company,
			String bodName) {
		this.fiscalYear = fiscalYear;
		this.bodType = bodType;
		this.company = company;
		this.bodName = bodName;
	}

	public Bod(FiscalYear fiscalYear, BodType bodType, Company company,
			String bodName, String bodType_1, String bodPost, String bodPhoto,
			String bodBio) {
		this.fiscalYear = fiscalYear;
		this.bodType = bodType;
		this.company = company;
		this.bodName = bodName;
		this.bodType_1 = bodType_1;
		this.bodPost = bodPost;
		this.bodPhoto = bodPhoto;
		this.bodBio = bodBio;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "bod_id", unique = true, nullable = false)
	public Integer getBodId() {
		return this.bodId;
	}

	public void setBodId(Integer bodId) {
		this.bodId = bodId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bod_fiscal_year_id", nullable = false)
	public FiscalYear getFiscalYear() {
		return this.fiscalYear;
	}

	public void setFiscalYear(FiscalYear fiscalYear) {
		this.fiscalYear = fiscalYear;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bod_type_id", nullable = false)
	public BodType getBodType() {
		return this.bodType;
	}

	public void setBodType(BodType bodType) {
		this.bodType = bodType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bod_company_id", nullable = false)
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@Column(name = "bod_name", nullable = false)
	public String getBodName() {
		return this.bodName;
	}

	public void setBodName(String bodName) {
		this.bodName = bodName;
	}

	@Column(name = "bod_type")
	public String getBodType_1() {
		return this.bodType_1;
	}

	public void setBodType_1(String bodType_1) {
		this.bodType_1 = bodType_1;
	}

	@Column(name = "bod_post")
	public String getBodPost() {
		return this.bodPost;
	}

	public void setBodPost(String bodPost) {
		this.bodPost = bodPost;
	}

	@Column(name = "bod_photo", length = 65535)
	public String getBodPhoto() {
		return this.bodPhoto;
	}

	public void setBodPhoto(String bodPhoto) {
		this.bodPhoto = bodPhoto;
	}

	@Column(name = "bod_bio", length = 65535)
	public String getBodBio() {
		return this.bodBio;
	}

	public void setBodBio(String bodBio) {
		this.bodBio = bodBio;
	}

}
