package com.nsmjsf.web.datamodels;

// Generated Feb 28, 2015 11:53:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BonusDividend generated by hbm2java
 */
@Entity
@Table(name = "bonus_dividend", catalog = "admin_nsmjsf")
public class BonusDividend implements java.io.Serializable {

	private Integer bonusDividendId;
	private Company company;
	private FiscalYear fiscalYear;
	private Float bonusDividendBonusSharePercent;
	private Float bonusDividendCashDividentPercent;
	private Float bonusDividendTotalDividend;
	private Date bonusDividendDistributionDate;

	public BonusDividend() {
	}

	public BonusDividend(Company company) {
		this.company = company;
	}

	public BonusDividend(Company company, FiscalYear fiscalYear,
			Float bonusDividendBonusSharePercent,
			Float bonusDividendCashDividentPercent,
			Float bonusDividendTotalDividend, Date bonusDividendDistributionDate) {
		this.company = company;
		this.fiscalYear = fiscalYear;
		this.bonusDividendBonusSharePercent = bonusDividendBonusSharePercent;
		this.bonusDividendCashDividentPercent = bonusDividendCashDividentPercent;
		this.bonusDividendTotalDividend = bonusDividendTotalDividend;
		this.bonusDividendDistributionDate = bonusDividendDistributionDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "bonus_dividend_id", unique = true, nullable = false)
	public Integer getBonusDividendId() {
		return this.bonusDividendId;
	}

	public void setBonusDividendId(Integer bonusDividendId) {
		this.bonusDividendId = bonusDividendId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bonus_dividend_company_id", nullable = false)
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bonus_dividend_fiscal_year_id")
	public FiscalYear getFiscalYear() {
		return this.fiscalYear;
	}

	public void setFiscalYear(FiscalYear fiscalYear) {
		this.fiscalYear = fiscalYear;
	}

	@Column(name = "bonus_dividend_bonus_share_percent", precision = 12, scale = 0)
	public Float getBonusDividendBonusSharePercent() {
		return this.bonusDividendBonusSharePercent;
	}

	public void setBonusDividendBonusSharePercent(
			Float bonusDividendBonusSharePercent) {
		this.bonusDividendBonusSharePercent = bonusDividendBonusSharePercent;
	}

	@Column(name = "bonus_dividend_cash_divident_percent", precision = 12, scale = 0)
	public Float getBonusDividendCashDividentPercent() {
		return this.bonusDividendCashDividentPercent;
	}

	public void setBonusDividendCashDividentPercent(
			Float bonusDividendCashDividentPercent) {
		this.bonusDividendCashDividentPercent = bonusDividendCashDividentPercent;
	}

	@Column(name = "bonus_dividend_total_dividend", precision = 12, scale = 0)
	public Float getBonusDividendTotalDividend() {
		return this.bonusDividendTotalDividend;
	}

	public void setBonusDividendTotalDividend(Float bonusDividendTotalDividend) {
		this.bonusDividendTotalDividend = bonusDividendTotalDividend;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "bonus_dividend_distribution_date", length = 0)
	public Date getBonusDividendDistributionDate() {
		return this.bonusDividendDistributionDate;
	}

	public void setBonusDividendDistributionDate(
			Date bonusDividendDistributionDate) {
		this.bonusDividendDistributionDate = bonusDividendDistributionDate;
	}

}
