package com.nsmjsf.web.datamodels;

// Generated Mar 2, 2015 3:36:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BonusDividendApproved generated by hbm2java
 */
@Entity
@Table(name = "bonus_dividend_approved", catalog = "admin_nsmjsf")
public class BonusDividendApproved implements java.io.Serializable {

	private Integer bonusDividendApprovedId;
	private Announcement announcement;
	private FiscalYear fiscalYear;
	private float bonusDividendApprovedBonus;
	private float bonusDividendApprovedDividend;
	private Date bonusDividendApprovedAgmDate;

	public BonusDividendApproved() {
	}

	public BonusDividendApproved(Announcement announcement,
			FiscalYear fiscalYear, float bonusDividendApprovedBonus,
			float bonusDividendApprovedDividend,
			Date bonusDividendApprovedAgmDate) {
		this.announcement = announcement;
		this.fiscalYear = fiscalYear;
		this.bonusDividendApprovedBonus = bonusDividendApprovedBonus;
		this.bonusDividendApprovedDividend = bonusDividendApprovedDividend;
		this.bonusDividendApprovedAgmDate = bonusDividendApprovedAgmDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "bonus_dividend_approved_id", unique = true, nullable = false)
	public Integer getBonusDividendApprovedId() {
		return this.bonusDividendApprovedId;
	}

	public void setBonusDividendApprovedId(Integer bonusDividendApprovedId) {
		this.bonusDividendApprovedId = bonusDividendApprovedId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bonus_dividend_approved_announcement_id", nullable = false)
	public Announcement getAnnouncement() {
		return this.announcement;
	}

	public void setAnnouncement(Announcement announcement) {
		this.announcement = announcement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bonus_dividend_approved_fiscal_year_id", nullable = false)
	public FiscalYear getFiscalYear() {
		return this.fiscalYear;
	}

	public void setFiscalYear(FiscalYear fiscalYear) {
		this.fiscalYear = fiscalYear;
	}

	@Column(name = "bonus_dividend_approved_bonus", nullable = false, precision = 12, scale = 0)
	public float getBonusDividendApprovedBonus() {
		return this.bonusDividendApprovedBonus;
	}

	public void setBonusDividendApprovedBonus(float bonusDividendApprovedBonus) {
		this.bonusDividendApprovedBonus = bonusDividendApprovedBonus;
	}

	@Column(name = "bonus_dividend_approved_dividend", nullable = false, precision = 12, scale = 0)
	public float getBonusDividendApprovedDividend() {
		return this.bonusDividendApprovedDividend;
	}

	public void setBonusDividendApprovedDividend(
			float bonusDividendApprovedDividend) {
		this.bonusDividendApprovedDividend = bonusDividendApprovedDividend;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "bonus_dividend_approved_agm_date", nullable = false, length = 0)
	public Date getBonusDividendApprovedAgmDate() {
		return this.bonusDividendApprovedAgmDate;
	}

	public void setBonusDividendApprovedAgmDate(
			Date bonusDividendApprovedAgmDate) {
		this.bonusDividendApprovedAgmDate = bonusDividendApprovedAgmDate;
	}

}
