package com.nsmjsf.web.datamodels;

// Generated Mar 14, 2015 9:52:11 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BullionPrice generated by hbm2java
 */
@Entity
@Table(name = "bullion_price", catalog = "admin_nsmjsf")
public class BullionPrice implements java.io.Serializable {

	private Integer bullionPriceId;
	private Post post;
	private int bullionPriceType;
	private Date bullionPriceDate;
	private int bullionPricePerUnit;

	public BullionPrice() {
	}

	public BullionPrice(Post post, int bullionPriceType, Date bullionPriceDate,
			int bullionPricePerUnit) {
		this.post = post;
		this.bullionPriceType = bullionPriceType;
		this.bullionPriceDate = bullionPriceDate;
		this.bullionPricePerUnit = bullionPricePerUnit;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "bullion_price_id", unique = true, nullable = false)
	public Integer getBullionPriceId() {
		return this.bullionPriceId;
	}

	public void setBullionPriceId(Integer bullionPriceId) {
		this.bullionPriceId = bullionPriceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bullion_price_post_id", nullable = false)
	public Post getPost() {
		return this.post;
	}

	public void setPost(Post post) {
		this.post = post;
	}

	@Column(name = "bullion_price_type", nullable = false)
	public int getBullionPriceType() {
		return this.bullionPriceType;
	}

	public void setBullionPriceType(int bullionPriceType) {
		this.bullionPriceType = bullionPriceType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "bullion_price_date", nullable = false, length = 0)
	public Date getBullionPriceDate() {
		return this.bullionPriceDate;
	}

	public void setBullionPriceDate(Date bullionPriceDate) {
		this.bullionPriceDate = bullionPriceDate;
	}

	@Column(name = "bullion_price_per_unit", nullable = false)
	public int getBullionPricePerUnit() {
		return this.bullionPricePerUnit;
	}

	public void setBullionPricePerUnit(int bullionPricePerUnit) {
		this.bullionPricePerUnit = bullionPricePerUnit;
	}

}
