package com.nsmjsf.web.datamodels;

// Generated Mar 2, 2015 3:36:21 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CertificateDividendDistribution generated by hbm2java
 */
@Entity
@Table(name = "certificate_dividend_distribution", catalog = "admin_nsmjsf")
public class CertificateDividendDistribution implements java.io.Serializable {

	private Integer certificateDividendDistributionId;
	private Announcement announcement;
	private IssueManager issueManager;
	private FiscalYear fiscalYear;
	private String certificateDividendDistributionDetail;

	public CertificateDividendDistribution() {
	}

	public CertificateDividendDistribution(Announcement announcement,
			IssueManager issueManager, FiscalYear fiscalYear) {
		this.announcement = announcement;
		this.issueManager = issueManager;
		this.fiscalYear = fiscalYear;
	}

	public CertificateDividendDistribution(Announcement announcement,
			IssueManager issueManager, FiscalYear fiscalYear,
			String certificateDividendDistributionDetail) {
		this.announcement = announcement;
		this.issueManager = issueManager;
		this.fiscalYear = fiscalYear;
		this.certificateDividendDistributionDetail = certificateDividendDistributionDetail;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "certificate_dividend_distribution_id", unique = true, nullable = false)
	public Integer getCertificateDividendDistributionId() {
		return this.certificateDividendDistributionId;
	}

	public void setCertificateDividendDistributionId(
			Integer certificateDividendDistributionId) {
		this.certificateDividendDistributionId = certificateDividendDistributionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "certificate_dividend_distribution_announcement_id", nullable = false)
	public Announcement getAnnouncement() {
		return this.announcement;
	}

	public void setAnnouncement(Announcement announcement) {
		this.announcement = announcement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "certificate_dividend_distribution_issue_manager_id", nullable = false)
	public IssueManager getIssueManager() {
		return this.issueManager;
	}

	public void setIssueManager(IssueManager issueManager) {
		this.issueManager = issueManager;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "certificate_dividend_distribution_fiscal_year_id", nullable = false)
	public FiscalYear getFiscalYear() {
		return this.fiscalYear;
	}

	public void setFiscalYear(FiscalYear fiscalYear) {
		this.fiscalYear = fiscalYear;
	}

	@Column(name = "certificate_dividend_distribution_detail", length = 65535)
	public String getCertificateDividendDistributionDetail() {
		return this.certificateDividendDistributionDetail;
	}

	public void setCertificateDividendDistributionDetail(
			String certificateDividendDistributionDetail) {
		this.certificateDividendDistributionDetail = certificateDividendDistributionDetail;
	}

}
