package com.nsmjsf.web.datamodels;

// Generated Feb 28, 2015 11:53:30 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CommentSocial generated by hbm2java
 */
@Entity
@Table(name = "comment_social", catalog = "admin_nsmjsf")
public class CommentSocial implements java.io.Serializable {

	private CommentSocialId id;
	private User user;
	private Comment comment;

	public CommentSocial() {
	}

	public CommentSocial(CommentSocialId id, User user, Comment comment) {
		this.id = id;
		this.user = user;
		this.comment = comment;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "commentSocialId", column = @Column(name = "comment_social_id", nullable = false)),
			@AttributeOverride(name = "commentSocialLike", column = @Column(name = "comment_social_like", nullable = false)),
			@AttributeOverride(name = "commentSocialDislike", column = @Column(name = "comment_social_dislike", nullable = false)),
			@AttributeOverride(name = "commentSocialUserId", column = @Column(name = "comment_social_user_id", nullable = false)),
			@AttributeOverride(name = "commentSocialCommentId", column = @Column(name = "comment_social_comment_id", nullable = false)) })
	public CommentSocialId getId() {
		return this.id;
	}

	public void setId(CommentSocialId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "comment_social_user_id", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "comment_social_comment_id", nullable = false, insertable = false, updatable = false)
	public Comment getComment() {
		return this.comment;
	}

	public void setComment(Comment comment) {
		this.comment = comment;
	}

}
