package com.nsmjsf.web.datamodels;

// Generated Feb 28, 2015 11:53:30 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CommentSocialId generated by hbm2java
 */
@Embeddable
public class CommentSocialId implements java.io.Serializable {

	private int commentSocialId;
	private boolean commentSocialLike;
	private boolean commentSocialDislike;
	private int commentSocialUserId;
	private int commentSocialCommentId;

	public CommentSocialId() {
	}

	public CommentSocialId(int commentSocialId, boolean commentSocialLike,
			boolean commentSocialDislike, int commentSocialUserId,
			int commentSocialCommentId) {
		this.commentSocialId = commentSocialId;
		this.commentSocialLike = commentSocialLike;
		this.commentSocialDislike = commentSocialDislike;
		this.commentSocialUserId = commentSocialUserId;
		this.commentSocialCommentId = commentSocialCommentId;
	}

	@Column(name = "comment_social_id", nullable = false)
	public int getCommentSocialId() {
		return this.commentSocialId;
	}

	public void setCommentSocialId(int commentSocialId) {
		this.commentSocialId = commentSocialId;
	}

	@Column(name = "comment_social_like", nullable = false)
	public boolean isCommentSocialLike() {
		return this.commentSocialLike;
	}

	public void setCommentSocialLike(boolean commentSocialLike) {
		this.commentSocialLike = commentSocialLike;
	}

	@Column(name = "comment_social_dislike", nullable = false)
	public boolean isCommentSocialDislike() {
		return this.commentSocialDislike;
	}

	public void setCommentSocialDislike(boolean commentSocialDislike) {
		this.commentSocialDislike = commentSocialDislike;
	}

	@Column(name = "comment_social_user_id", nullable = false)
	public int getCommentSocialUserId() {
		return this.commentSocialUserId;
	}

	public void setCommentSocialUserId(int commentSocialUserId) {
		this.commentSocialUserId = commentSocialUserId;
	}

	@Column(name = "comment_social_comment_id", nullable = false)
	public int getCommentSocialCommentId() {
		return this.commentSocialCommentId;
	}

	public void setCommentSocialCommentId(int commentSocialCommentId) {
		this.commentSocialCommentId = commentSocialCommentId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CommentSocialId))
			return false;
		CommentSocialId castOther = (CommentSocialId) other;

		return (this.getCommentSocialId() == castOther.getCommentSocialId())
				&& (this.isCommentSocialLike() == castOther
						.isCommentSocialLike())
				&& (this.isCommentSocialDislike() == castOther
						.isCommentSocialDislike())
				&& (this.getCommentSocialUserId() == castOther
						.getCommentSocialUserId())
				&& (this.getCommentSocialCommentId() == castOther
						.getCommentSocialCommentId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCommentSocialId();
		result = 37 * result + (this.isCommentSocialLike() ? 1 : 0);
		result = 37 * result + (this.isCommentSocialDislike() ? 1 : 0);
		result = 37 * result + this.getCommentSocialUserId();
		result = 37 * result + this.getCommentSocialCommentId();
		return result;
	}

}
