package com.nsmjsf.web.datamodels;

// Generated Feb 28, 2015 11:53:30 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ContentSource generated by hbm2java
 */
@Entity
@Table(name = "content_source", catalog = "admin_nsmjsf")
public class ContentSource implements java.io.Serializable {

	private Integer contentSourceId;
	private Post post;
	private String contentSourceAuthor;
	private String contentSourceLink;
	private String contentSourceAuthorImage;

	public ContentSource() {
	}

	public ContentSource(Post post, String contentSourceAuthor,
			String contentSourceLink, String contentSourceAuthorImage) {
		this.post = post;
		this.contentSourceAuthor = contentSourceAuthor;
		this.contentSourceLink = contentSourceLink;
		this.contentSourceAuthorImage = contentSourceAuthorImage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "content_source_id", unique = true, nullable = false)
	public Integer getContentSourceId() {
		return this.contentSourceId;
	}

	public void setContentSourceId(Integer contentSourceId) {
		this.contentSourceId = contentSourceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "content_source_post_id", nullable = false)
	public Post getPost() {
		return this.post;
	}

	public void setPost(Post post) {
		this.post = post;
	}

	@Column(name = "content_source_author", nullable = false)
	public String getContentSourceAuthor() {
		return this.contentSourceAuthor;
	}

	public void setContentSourceAuthor(String contentSourceAuthor) {
		this.contentSourceAuthor = contentSourceAuthor;
	}

	@Column(name = "content_source_link", nullable = false, length = 65535)
	public String getContentSourceLink() {
		return this.contentSourceLink;
	}

	public void setContentSourceLink(String contentSourceLink) {
		this.contentSourceLink = contentSourceLink;
	}

	@Column(name = "content_source_author_image", nullable = false, length = 65535)
	public String getContentSourceAuthorImage() {
		return this.contentSourceAuthorImage;
	}

	public void setContentSourceAuthorImage(String contentSourceAuthorImage) {
		this.contentSourceAuthorImage = contentSourceAuthorImage;
	}

}
