package com.nsmjsf.web.datamodels;

// Generated Mar 2, 2015 3:36:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EnergyType generated by hbm2java
 */
@Entity
@Table(name = "energy_type", catalog = "admin_nsmjsf")
public class EnergyType implements java.io.Serializable {

	private Integer energyTypeId;
	private String energyTypeLabel;
	private Set<UserEnergy> userEnergies = new HashSet<UserEnergy>(0);

	public EnergyType() {
	}

	public EnergyType(String energyTypeLabel) {
		this.energyTypeLabel = energyTypeLabel;
	}

	public EnergyType(String energyTypeLabel, Set<UserEnergy> userEnergies) {
		this.energyTypeLabel = energyTypeLabel;
		this.userEnergies = userEnergies;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "energy_type_id", unique = true, nullable = false)
	public Integer getEnergyTypeId() {
		return this.energyTypeId;
	}

	public void setEnergyTypeId(Integer energyTypeId) {
		this.energyTypeId = energyTypeId;
	}

	@Column(name = "energy_type_label", nullable = false)
	public String getEnergyTypeLabel() {
		return this.energyTypeLabel;
	}

	public void setEnergyTypeLabel(String energyTypeLabel) {
		this.energyTypeLabel = energyTypeLabel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "energyType")
	public Set<UserEnergy> getUserEnergies() {
		return this.userEnergies;
	}

	public void setUserEnergies(Set<UserEnergy> userEnergies) {
		this.userEnergies = userEnergies;
	}

}
