package com.nsmjsf.web.datamodels;

// Generated Mar 14, 2015 9:52:11 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EnergyPrice generated by hbm2java
 */
@Entity
@Table(name = "energy_price", catalog = "admin_nsmjsf")
public class EnergyPrice implements java.io.Serializable {

	private Integer energyPriceId;
	private int energyPriceType;
	private Date energyPriceDate;
	private float energyPricePrice;
	private String energyPriceUnit;

	public EnergyPrice() {
	}

	public EnergyPrice(int energyPriceType, Date energyPriceDate,
			float energyPricePrice, String energyPriceUnit) {
		this.energyPriceType = energyPriceType;
		this.energyPriceDate = energyPriceDate;
		this.energyPricePrice = energyPricePrice;
		this.energyPriceUnit = energyPriceUnit;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "energy_price_id", unique = true, nullable = false)
	public Integer getEnergyPriceId() {
		return this.energyPriceId;
	}

	public void setEnergyPriceId(Integer energyPriceId) {
		this.energyPriceId = energyPriceId;
	}

	@Column(name = "energy_price_type", nullable = false)
	public int getEnergyPriceType() {
		return this.energyPriceType;
	}

	public void setEnergyPriceType(int energyPriceType) {
		this.energyPriceType = energyPriceType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "energy_price_date", nullable = false, length = 0)
	public Date getEnergyPriceDate() {
		return this.energyPriceDate;
	}

	public void setEnergyPriceDate(Date energyPriceDate) {
		this.energyPriceDate = energyPriceDate;
	}

	@Column(name = "energy_price_price", nullable = false, precision = 12, scale = 0)
	public float getEnergyPricePrice() {
		return this.energyPricePrice;
	}

	public void setEnergyPricePrice(float energyPricePrice) {
		this.energyPricePrice = energyPricePrice;
	}

	@Column(name = "energy_price_unit", nullable = false)
	public String getEnergyPriceUnit() {
		return this.energyPriceUnit;
	}

	public void setEnergyPriceUnit(String energyPriceUnit) {
		this.energyPriceUnit = energyPriceUnit;
	}

}
