package com.nsmjsf.web.datamodels;

// Generated Mar 2, 2015 3:36:21 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FloorsheetHeader generated by hbm2java
 */
@Entity
@Table(name = "floorsheet_header", catalog = "admin_nsmjsf")
public class FloorsheetHeader implements java.io.Serializable {

	private Integer floorsheetHeaderId;
	private String floorsheetHeaderColumn;
	private String floorsheetHeaderText;

	public FloorsheetHeader() {
	}

	public FloorsheetHeader(String floorsheetHeaderColumn,
			String floorsheetHeaderText) {
		this.floorsheetHeaderColumn = floorsheetHeaderColumn;
		this.floorsheetHeaderText = floorsheetHeaderText;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "floorsheet_header_id", unique = true, nullable = false)
	public Integer getFloorsheetHeaderId() {
		return this.floorsheetHeaderId;
	}

	public void setFloorsheetHeaderId(Integer floorsheetHeaderId) {
		this.floorsheetHeaderId = floorsheetHeaderId;
	}

	@Column(name = "floorsheet_header_column", nullable = false, length = 25)
	public String getFloorsheetHeaderColumn() {
		return this.floorsheetHeaderColumn;
	}

	public void setFloorsheetHeaderColumn(String floorsheetHeaderColumn) {
		this.floorsheetHeaderColumn = floorsheetHeaderColumn;
	}

	@Column(name = "floorsheet_header_text", nullable = false, length = 25)
	public String getFloorsheetHeaderText() {
		return this.floorsheetHeaderText;
	}

	public void setFloorsheetHeaderText(String floorsheetHeaderText) {
		this.floorsheetHeaderText = floorsheetHeaderText;
	}

}
