package com.nsmjsf.web.datamodels;

// Generated Mar 2, 2015 3:36:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * IssueType generated by hbm2java
 */
@Entity
@Table(name = "issue_type", catalog = "admin_nsmjsf")
public class IssueType implements java.io.Serializable {

	private Integer issueTypeId;
	private String issueTypeLabel;
	private Set<Issue> issues = new HashSet<Issue>(0);

	public IssueType() {
	}

	public IssueType(String issueTypeLabel) {
		this.issueTypeLabel = issueTypeLabel;
	}

	public IssueType(String issueTypeLabel, Set<Issue> issues) {
		this.issueTypeLabel = issueTypeLabel;
		this.issues = issues;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "issue_type_id", unique = true, nullable = false)
	public Integer getIssueTypeId() {
		return this.issueTypeId;
	}

	public void setIssueTypeId(Integer issueTypeId) {
		this.issueTypeId = issueTypeId;
	}

	@Column(name = "issue_type_label", nullable = false)
	public String getIssueTypeLabel() {
		return this.issueTypeLabel;
	}

	public void setIssueTypeLabel(String issueTypeLabel) {
		this.issueTypeLabel = issueTypeLabel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "issueType")
	public Set<Issue> getIssues() {
		return this.issues;
	}

	public void setIssues(Set<Issue> issues) {
		this.issues = issues;
	}

}
