package com.nsmjsf.web.datamodels;

// Generated Mar 2, 2015 3:36:21 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * KeyRatio generated by hbm2java
 */
@Entity
@Table(name = "key_ratio", catalog = "admin_nsmjsf")
public class KeyRatio implements java.io.Serializable {

	private Integer keyRatioId;
	private FinancialReport financialReport;
	private float keyRatioNetProfitToGrossIncome;
	private float keyRatioEarningPerShare;
	private float keyRatioMarketValuePerShare;
	private float keyRatioPriceEarningRatio;
	private float keyRatioDividendOnShareCapital;
	private float keyRatioCapitalAdequacyFund;
	private float keyRatioCashDividend;
	private float keyRatioInterestIncomeToLoanAndAdvance;
	private float keyRatioStaffExpensesToTotalOperatingExpenses;
	private float keyRatioInterestExpensesToTotalDepositAndBorrow;
	private float keyRatioExchangeGainToTotalAssets;
	private float keyRatioExchangeFluctuationIncomeByTotalIncome;
	private float keyRatioStaffBonusToTotalStaffExpenses;
	private float keyRatioNetProfitToLoanAndAdvance;
	private float keyRatioNetProfitToTotalAssets;
	private float keyRatioCdRatio;
	private float keyRatioTotalOperatingExpensesToTotalAssets;
	private float keyRatioCoreCapital;
	private float keyRatioSupplementaryCapital;
	private float keyRatioTotalCapitalFund;
	private float keyRatioLiquidity;
	private float keyRatioNonperformingLoanToTotalLoan;
	private float keyRatioWeightedAverageInterestRateSpread;
	private float keyRatioReturnOfAsset;
	private float keyRatioBookNetWorth;
	private float keyRatioBookNetWorthPerShare;
	private float keyRatioTotalShares;
	private float keyRatioTotalStaff;
	private float keyRatioReturnOnEquity;

	public KeyRatio() {
	}

	public KeyRatio(FinancialReport financialReport,
			float keyRatioNetProfitToGrossIncome,
			float keyRatioEarningPerShare, float keyRatioMarketValuePerShare,
			float keyRatioPriceEarningRatio,
			float keyRatioDividendOnShareCapital,
			float keyRatioCapitalAdequacyFund, float keyRatioCashDividend,
			float keyRatioInterestIncomeToLoanAndAdvance,
			float keyRatioStaffExpensesToTotalOperatingExpenses,
			float keyRatioInterestExpensesToTotalDepositAndBorrow,
			float keyRatioExchangeGainToTotalAssets,
			float keyRatioExchangeFluctuationIncomeByTotalIncome,
			float keyRatioStaffBonusToTotalStaffExpenses,
			float keyRatioNetProfitToLoanAndAdvance,
			float keyRatioNetProfitToTotalAssets, float keyRatioCdRatio,
			float keyRatioTotalOperatingExpensesToTotalAssets,
			float keyRatioCoreCapital, float keyRatioSupplementaryCapital,
			float keyRatioTotalCapitalFund, float keyRatioLiquidity,
			float keyRatioNonperformingLoanToTotalLoan,
			float keyRatioWeightedAverageInterestRateSpread,
			float keyRatioReturnOfAsset, float keyRatioBookNetWorth,
			float keyRatioBookNetWorthPerShare, float keyRatioTotalShares,
			float keyRatioTotalStaff, float keyRatioReturnOnEquity) {
		this.financialReport = financialReport;
		this.keyRatioNetProfitToGrossIncome = keyRatioNetProfitToGrossIncome;
		this.keyRatioEarningPerShare = keyRatioEarningPerShare;
		this.keyRatioMarketValuePerShare = keyRatioMarketValuePerShare;
		this.keyRatioPriceEarningRatio = keyRatioPriceEarningRatio;
		this.keyRatioDividendOnShareCapital = keyRatioDividendOnShareCapital;
		this.keyRatioCapitalAdequacyFund = keyRatioCapitalAdequacyFund;
		this.keyRatioCashDividend = keyRatioCashDividend;
		this.keyRatioInterestIncomeToLoanAndAdvance = keyRatioInterestIncomeToLoanAndAdvance;
		this.keyRatioStaffExpensesToTotalOperatingExpenses = keyRatioStaffExpensesToTotalOperatingExpenses;
		this.keyRatioInterestExpensesToTotalDepositAndBorrow = keyRatioInterestExpensesToTotalDepositAndBorrow;
		this.keyRatioExchangeGainToTotalAssets = keyRatioExchangeGainToTotalAssets;
		this.keyRatioExchangeFluctuationIncomeByTotalIncome = keyRatioExchangeFluctuationIncomeByTotalIncome;
		this.keyRatioStaffBonusToTotalStaffExpenses = keyRatioStaffBonusToTotalStaffExpenses;
		this.keyRatioNetProfitToLoanAndAdvance = keyRatioNetProfitToLoanAndAdvance;
		this.keyRatioNetProfitToTotalAssets = keyRatioNetProfitToTotalAssets;
		this.keyRatioCdRatio = keyRatioCdRatio;
		this.keyRatioTotalOperatingExpensesToTotalAssets = keyRatioTotalOperatingExpensesToTotalAssets;
		this.keyRatioCoreCapital = keyRatioCoreCapital;
		this.keyRatioSupplementaryCapital = keyRatioSupplementaryCapital;
		this.keyRatioTotalCapitalFund = keyRatioTotalCapitalFund;
		this.keyRatioLiquidity = keyRatioLiquidity;
		this.keyRatioNonperformingLoanToTotalLoan = keyRatioNonperformingLoanToTotalLoan;
		this.keyRatioWeightedAverageInterestRateSpread = keyRatioWeightedAverageInterestRateSpread;
		this.keyRatioReturnOfAsset = keyRatioReturnOfAsset;
		this.keyRatioBookNetWorth = keyRatioBookNetWorth;
		this.keyRatioBookNetWorthPerShare = keyRatioBookNetWorthPerShare;
		this.keyRatioTotalShares = keyRatioTotalShares;
		this.keyRatioTotalStaff = keyRatioTotalStaff;
		this.keyRatioReturnOnEquity = keyRatioReturnOnEquity;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "key_ratio_id", unique = true, nullable = false)
	public Integer getKeyRatioId() {
		return this.keyRatioId;
	}

	public void setKeyRatioId(Integer keyRatioId) {
		this.keyRatioId = keyRatioId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "key_ratio_financial_report_id", nullable = false)
	public FinancialReport getFinancialReport() {
		return this.financialReport;
	}

	public void setFinancialReport(FinancialReport financialReport) {
		this.financialReport = financialReport;
	}

	@Column(name = "key_ratio_net_profit_to_gross_income", nullable = false, precision = 12, scale = 0)
	public float getKeyRatioNetProfitToGrossIncome() {
		return this.keyRatioNetProfitToGrossIncome;
	}

	public void setKeyRatioNetProfitToGrossIncome(
			float keyRatioNetProfitToGrossIncome) {
		this.keyRatioNetProfitToGrossIncome = keyRatioNetProfitToGrossIncome;
	}

	@Column(name = "key_ratio_earning_per_share", nullable = false, precision = 12, scale = 0)
	public float getKeyRatioEarningPerShare() {
		return this.keyRatioEarningPerShare;
	}

	public void setKeyRatioEarningPerShare(float keyRatioEarningPerShare) {
		this.keyRatioEarningPerShare = keyRatioEarningPerShare;
	}

	@Column(name = "key_ratio_market_value_per_share", nullable = false, precision = 12, scale = 0)
	public float getKeyRatioMarketValuePerShare() {
		return this.keyRatioMarketValuePerShare;
	}

	public void setKeyRatioMarketValuePerShare(float keyRatioMarketValuePerShare) {
		this.keyRatioMarketValuePerShare = keyRatioMarketValuePerShare;
	}

	@Column(name = "key_ratio_price_earning_ratio", nullable = false, precision = 12, scale = 0)
	public float getKeyRatioPriceEarningRatio() {
		return this.keyRatioPriceEarningRatio;
	}

	public void setKeyRatioPriceEarningRatio(float keyRatioPriceEarningRatio) {
		this.keyRatioPriceEarningRatio = keyRatioPriceEarningRatio;
	}

	@Column(name = "key_ratio_dividend_on_share_capital", nullable = false, precision = 12, scale = 0)
	public float getKeyRatioDividendOnShareCapital() {
		return this.keyRatioDividendOnShareCapital;
	}

	public void setKeyRatioDividendOnShareCapital(
			float keyRatioDividendOnShareCapital) {
		this.keyRatioDividendOnShareCapital = keyRatioDividendOnShareCapital;
	}

	@Column(name = "key_ratio_capital_adequacy_fund", nullable = false, precision = 12, scale = 0)
	public float getKeyRatioCapitalAdequacyFund() {
		return this.keyRatioCapitalAdequacyFund;
	}

	public void setKeyRatioCapitalAdequacyFund(float keyRatioCapitalAdequacyFund) {
		this.keyRatioCapitalAdequacyFund = keyRatioCapitalAdequacyFund;
	}

	@Column(name = "key_ratio_cash_dividend", nullable = false, precision = 12, scale = 0)
	public float getKeyRatioCashDividend() {
		return this.keyRatioCashDividend;
	}

	public void setKeyRatioCashDividend(float keyRatioCashDividend) {
		this.keyRatioCashDividend = keyRatioCashDividend;
	}

	@Column(name = "key_ratio_interest_income_to_loan_and_advance", nullable = false, precision = 12, scale = 0)
	public float getKeyRatioInterestIncomeToLoanAndAdvance() {
		return this.keyRatioInterestIncomeToLoanAndAdvance;
	}

	public void setKeyRatioInterestIncomeToLoanAndAdvance(
			float keyRatioInterestIncomeToLoanAndAdvance) {
		this.keyRatioInterestIncomeToLoanAndAdvance = keyRatioInterestIncomeToLoanAndAdvance;
	}

	@Column(name = "key_ratio_staff_expenses_to_total_operating_expenses", nullable = false, precision = 12, scale = 0)
	public float getKeyRatioStaffExpensesToTotalOperatingExpenses() {
		return this.keyRatioStaffExpensesToTotalOperatingExpenses;
	}

	public void setKeyRatioStaffExpensesToTotalOperatingExpenses(
			float keyRatioStaffExpensesToTotalOperatingExpenses) {
		this.keyRatioStaffExpensesToTotalOperatingExpenses = keyRatioStaffExpensesToTotalOperatingExpenses;
	}

	@Column(name = "key_ratio_interest_expenses_to_total_deposit_and_borrow", nullable = false, precision = 12, scale = 0)
	public float getKeyRatioInterestExpensesToTotalDepositAndBorrow() {
		return this.keyRatioInterestExpensesToTotalDepositAndBorrow;
	}

	public void setKeyRatioInterestExpensesToTotalDepositAndBorrow(
			float keyRatioInterestExpensesToTotalDepositAndBorrow) {
		this.keyRatioInterestExpensesToTotalDepositAndBorrow = keyRatioInterestExpensesToTotalDepositAndBorrow;
	}

	@Column(name = "key_ratio_exchange_gain_to_total_assets", nullable = false, precision = 12, scale = 0)
	public float getKeyRatioExchangeGainToTotalAssets() {
		return this.keyRatioExchangeGainToTotalAssets;
	}

	public void setKeyRatioExchangeGainToTotalAssets(
			float keyRatioExchangeGainToTotalAssets) {
		this.keyRatioExchangeGainToTotalAssets = keyRatioExchangeGainToTotalAssets;
	}

	@Column(name = "key_ratio_exchange_fluctuation_income_by_total_income", nullable = false, precision = 12, scale = 0)
	public float getKeyRatioExchangeFluctuationIncomeByTotalIncome() {
		return this.keyRatioExchangeFluctuationIncomeByTotalIncome;
	}

	public void setKeyRatioExchangeFluctuationIncomeByTotalIncome(
			float keyRatioExchangeFluctuationIncomeByTotalIncome) {
		this.keyRatioExchangeFluctuationIncomeByTotalIncome = keyRatioExchangeFluctuationIncomeByTotalIncome;
	}

	@Column(name = "key_ratio_staff_bonus_to_total_staff_expenses", nullable = false, precision = 12, scale = 0)
	public float getKeyRatioStaffBonusToTotalStaffExpenses() {
		return this.keyRatioStaffBonusToTotalStaffExpenses;
	}

	public void setKeyRatioStaffBonusToTotalStaffExpenses(
			float keyRatioStaffBonusToTotalStaffExpenses) {
		this.keyRatioStaffBonusToTotalStaffExpenses = keyRatioStaffBonusToTotalStaffExpenses;
	}

	@Column(name = "key_ratio_net_profit_to_loan_and_advance", nullable = false, precision = 12, scale = 0)
	public float getKeyRatioNetProfitToLoanAndAdvance() {
		return this.keyRatioNetProfitToLoanAndAdvance;
	}

	public void setKeyRatioNetProfitToLoanAndAdvance(
			float keyRatioNetProfitToLoanAndAdvance) {
		this.keyRatioNetProfitToLoanAndAdvance = keyRatioNetProfitToLoanAndAdvance;
	}

	@Column(name = "key_ratio_net_profit_to_total_assets", nullable = false, precision = 12, scale = 0)
	public float getKeyRatioNetProfitToTotalAssets() {
		return this.keyRatioNetProfitToTotalAssets;
	}

	public void setKeyRatioNetProfitToTotalAssets(
			float keyRatioNetProfitToTotalAssets) {
		this.keyRatioNetProfitToTotalAssets = keyRatioNetProfitToTotalAssets;
	}

	@Column(name = "key_ratio_cd_ratio", nullable = false, precision = 12, scale = 0)
	public float getKeyRatioCdRatio() {
		return this.keyRatioCdRatio;
	}

	public void setKeyRatioCdRatio(float keyRatioCdRatio) {
		this.keyRatioCdRatio = keyRatioCdRatio;
	}

	@Column(name = "key_ratio_total_operating_expenses_to_total_assets", nullable = false, precision = 12, scale = 0)
	public float getKeyRatioTotalOperatingExpensesToTotalAssets() {
		return this.keyRatioTotalOperatingExpensesToTotalAssets;
	}

	public void setKeyRatioTotalOperatingExpensesToTotalAssets(
			float keyRatioTotalOperatingExpensesToTotalAssets) {
		this.keyRatioTotalOperatingExpensesToTotalAssets = keyRatioTotalOperatingExpensesToTotalAssets;
	}

	@Column(name = "key_ratio_core_capital", nullable = false, precision = 12, scale = 0)
	public float getKeyRatioCoreCapital() {
		return this.keyRatioCoreCapital;
	}

	public void setKeyRatioCoreCapital(float keyRatioCoreCapital) {
		this.keyRatioCoreCapital = keyRatioCoreCapital;
	}

	@Column(name = "key_ratio_supplementary_capital", nullable = false, precision = 12, scale = 0)
	public float getKeyRatioSupplementaryCapital() {
		return this.keyRatioSupplementaryCapital;
	}

	public void setKeyRatioSupplementaryCapital(
			float keyRatioSupplementaryCapital) {
		this.keyRatioSupplementaryCapital = keyRatioSupplementaryCapital;
	}

	@Column(name = "key_ratio_total_capital_fund", nullable = false, precision = 12, scale = 0)
	public float getKeyRatioTotalCapitalFund() {
		return this.keyRatioTotalCapitalFund;
	}

	public void setKeyRatioTotalCapitalFund(float keyRatioTotalCapitalFund) {
		this.keyRatioTotalCapitalFund = keyRatioTotalCapitalFund;
	}

	@Column(name = "key_ratio_liquidity", nullable = false, precision = 12, scale = 0)
	public float getKeyRatioLiquidity() {
		return this.keyRatioLiquidity;
	}

	public void setKeyRatioLiquidity(float keyRatioLiquidity) {
		this.keyRatioLiquidity = keyRatioLiquidity;
	}

	@Column(name = "key_ratio_nonperforming_loan_to_total_loan", nullable = false, precision = 12, scale = 0)
	public float getKeyRatioNonperformingLoanToTotalLoan() {
		return this.keyRatioNonperformingLoanToTotalLoan;
	}

	public void setKeyRatioNonperformingLoanToTotalLoan(
			float keyRatioNonperformingLoanToTotalLoan) {
		this.keyRatioNonperformingLoanToTotalLoan = keyRatioNonperformingLoanToTotalLoan;
	}

	@Column(name = "key_ratio_weighted_average_interest_rate_spread", nullable = false, precision = 12, scale = 0)
	public float getKeyRatioWeightedAverageInterestRateSpread() {
		return this.keyRatioWeightedAverageInterestRateSpread;
	}

	public void setKeyRatioWeightedAverageInterestRateSpread(
			float keyRatioWeightedAverageInterestRateSpread) {
		this.keyRatioWeightedAverageInterestRateSpread = keyRatioWeightedAverageInterestRateSpread;
	}

	@Column(name = "key_ratio_return_of_asset", nullable = false, precision = 12, scale = 0)
	public float getKeyRatioReturnOfAsset() {
		return this.keyRatioReturnOfAsset;
	}

	public void setKeyRatioReturnOfAsset(float keyRatioReturnOfAsset) {
		this.keyRatioReturnOfAsset = keyRatioReturnOfAsset;
	}

	@Column(name = "key_ratio_book_net_worth", nullable = false, precision = 12, scale = 0)
	public float getKeyRatioBookNetWorth() {
		return this.keyRatioBookNetWorth;
	}

	public void setKeyRatioBookNetWorth(float keyRatioBookNetWorth) {
		this.keyRatioBookNetWorth = keyRatioBookNetWorth;
	}

	@Column(name = "key_ratio_book_net_worth_per_share", nullable = false, precision = 12, scale = 0)
	public float getKeyRatioBookNetWorthPerShare() {
		return this.keyRatioBookNetWorthPerShare;
	}

	public void setKeyRatioBookNetWorthPerShare(
			float keyRatioBookNetWorthPerShare) {
		this.keyRatioBookNetWorthPerShare = keyRatioBookNetWorthPerShare;
	}

	@Column(name = "key_ratio_total_shares", nullable = false, precision = 12, scale = 0)
	public float getKeyRatioTotalShares() {
		return this.keyRatioTotalShares;
	}

	public void setKeyRatioTotalShares(float keyRatioTotalShares) {
		this.keyRatioTotalShares = keyRatioTotalShares;
	}

	@Column(name = "key_ratio_total_staff", nullable = false, precision = 12, scale = 0)
	public float getKeyRatioTotalStaff() {
		return this.keyRatioTotalStaff;
	}

	public void setKeyRatioTotalStaff(float keyRatioTotalStaff) {
		this.keyRatioTotalStaff = keyRatioTotalStaff;
	}

	@Column(name = "key_ratio_return_on_equity", nullable = false, precision = 12, scale = 0)
	public float getKeyRatioReturnOnEquity() {
		return this.keyRatioReturnOnEquity;
	}

	public void setKeyRatioReturnOnEquity(float keyRatioReturnOnEquity) {
		this.keyRatioReturnOnEquity = keyRatioReturnOnEquity;
	}

}
