package com.nsmjsf.web.datamodels;

// Generated Feb 28, 2015 11:53:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LatestPrice generated by hbm2java
 */
@Entity
@Table(name = "latest_price", catalog = "admin_nsmjsf")
public class LatestPrice implements java.io.Serializable {

	private Integer latestPriceId;
	private Post post;
	private Company company;
	private int latestPriceNoOfTransactions;
	private float latestPriceMaxPrice;
	private float latestPriceMinPrice;
	private float latestPriceClosePrice;
	private int latestPriceTotalShare;
	private float latestPriceAmount;
	private float latestPricePrevClosing;
	private float latestPriceDiff;
	private Date latestPriceTradedDate;
	private boolean latestPriceDeleted;

	public LatestPrice() {
	}

	public LatestPrice(Post post, Company company,
			int latestPriceNoOfTransactions, float latestPriceMaxPrice,
			float latestPriceMinPrice, float latestPriceClosePrice,
			int latestPriceTotalShare, float latestPriceAmount,
			float latestPricePrevClosing, float latestPriceDiff,
			Date latestPriceTradedDate, boolean latestPriceDeleted) {
		this.post = post;
		this.company = company;
		this.latestPriceNoOfTransactions = latestPriceNoOfTransactions;
		this.latestPriceMaxPrice = latestPriceMaxPrice;
		this.latestPriceMinPrice = latestPriceMinPrice;
		this.latestPriceClosePrice = latestPriceClosePrice;
		this.latestPriceTotalShare = latestPriceTotalShare;
		this.latestPriceAmount = latestPriceAmount;
		this.latestPricePrevClosing = latestPricePrevClosing;
		this.latestPriceDiff = latestPriceDiff;
		this.latestPriceTradedDate = latestPriceTradedDate;
		this.latestPriceDeleted = latestPriceDeleted;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "latest_price_id", unique = true, nullable = false)
	public Integer getLatestPriceId() {
		return this.latestPriceId;
	}

	public void setLatestPriceId(Integer latestPriceId) {
		this.latestPriceId = latestPriceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "latest_price_post_id", nullable = false)
	public Post getPost() {
		return this.post;
	}

	public void setPost(Post post) {
		this.post = post;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "latest_price_company_id", nullable = false)
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@Column(name = "latest_price_no_of_transactions", nullable = false)
	public int getLatestPriceNoOfTransactions() {
		return this.latestPriceNoOfTransactions;
	}

	public void setLatestPriceNoOfTransactions(int latestPriceNoOfTransactions) {
		this.latestPriceNoOfTransactions = latestPriceNoOfTransactions;
	}

	@Column(name = "latest_price_max_price", nullable = false, precision = 12, scale = 0)
	public float getLatestPriceMaxPrice() {
		return this.latestPriceMaxPrice;
	}

	public void setLatestPriceMaxPrice(float latestPriceMaxPrice) {
		this.latestPriceMaxPrice = latestPriceMaxPrice;
	}

	@Column(name = "latest_price_min_price", nullable = false, precision = 12, scale = 0)
	public float getLatestPriceMinPrice() {
		return this.latestPriceMinPrice;
	}

	public void setLatestPriceMinPrice(float latestPriceMinPrice) {
		this.latestPriceMinPrice = latestPriceMinPrice;
	}

	@Column(name = "latest_price_close_price", nullable = false, precision = 12, scale = 0)
	public float getLatestPriceClosePrice() {
		return this.latestPriceClosePrice;
	}

	public void setLatestPriceClosePrice(float latestPriceClosePrice) {
		this.latestPriceClosePrice = latestPriceClosePrice;
	}

	@Column(name = "latest_price_total_share", nullable = false)
	public int getLatestPriceTotalShare() {
		return this.latestPriceTotalShare;
	}

	public void setLatestPriceTotalShare(int latestPriceTotalShare) {
		this.latestPriceTotalShare = latestPriceTotalShare;
	}

	@Column(name = "latest_price_amount", nullable = false, precision = 12, scale = 0)
	public float getLatestPriceAmount() {
		return this.latestPriceAmount;
	}

	public void setLatestPriceAmount(float latestPriceAmount) {
		this.latestPriceAmount = latestPriceAmount;
	}

	@Column(name = "latest_price_prev_closing", nullable = false, precision = 12, scale = 0)
	public float getLatestPricePrevClosing() {
		return this.latestPricePrevClosing;
	}

	public void setLatestPricePrevClosing(float latestPricePrevClosing) {
		this.latestPricePrevClosing = latestPricePrevClosing;
	}

	@Column(name = "latest_price_diff", nullable = false, precision = 12, scale = 0)
	public float getLatestPriceDiff() {
		return this.latestPriceDiff;
	}

	public void setLatestPriceDiff(float latestPriceDiff) {
		this.latestPriceDiff = latestPriceDiff;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "latest_price_traded_date", nullable = false, length = 0)
	public Date getLatestPriceTradedDate() {
		return this.latestPriceTradedDate;
	}

	public void setLatestPriceTradedDate(Date latestPriceTradedDate) {
		this.latestPriceTradedDate = latestPriceTradedDate;
	}

	@Column(name = "latest_price_deleted", nullable = false)
	public boolean isLatestPriceDeleted() {
		return this.latestPriceDeleted;
	}

	public void setLatestPriceDeleted(boolean latestPriceDeleted) {
		this.latestPriceDeleted = latestPriceDeleted;
	}

}
