package com.nsmjsf.web.datamodels;

// Generated Feb 28, 2015 11:53:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MarketIndex generated by hbm2java
 */
@Entity
@Table(name = "market_index", catalog = "admin_nsmjsf")
public class MarketIndex implements java.io.Serializable {

	private Integer indexValueId;
	private IndexType indexType;
	private float indexValueValue;
	private Date indexValueDate;

	public MarketIndex() {
	}

	public MarketIndex(IndexType indexType, float indexValueValue,
			Date indexValueDate) {
		this.indexType = indexType;
		this.indexValueValue = indexValueValue;
		this.indexValueDate = indexValueDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "index_value_id", unique = true, nullable = false)
	public Integer getIndexValueId() {
		return this.indexValueId;
	}

	public void setIndexValueId(Integer indexValueId) {
		this.indexValueId = indexValueId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "market_index_type_id", nullable = false)
	public IndexType getIndexType() {
		return this.indexType;
	}

	public void setIndexType(IndexType indexType) {
		this.indexType = indexType;
	}

	@Column(name = "index_value_value", nullable = false, precision = 12, scale = 0)
	public float getIndexValueValue() {
		return this.indexValueValue;
	}

	public void setIndexValueValue(float indexValueValue) {
		this.indexValueValue = indexValueValue;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "index_value_date", nullable = false, length = 0)
	public Date getIndexValueDate() {
		return this.indexValueDate;
	}

	public void setIndexValueDate(Date indexValueDate) {
		this.indexValueDate = indexValueDate;
	}

}
