package com.nsmjsf.web.datamodels;

// Generated Feb 28, 2015 11:53:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Month generated by hbm2java
 */
@Entity
@Table(name = "month", catalog = "admin_nsmjsf")
public class Month implements java.io.Serializable {

	private int monthId;
	private String monthLabel;
	private Set<MonthlyFinancialHighlight> monthlyFinancialHighlights = new HashSet<MonthlyFinancialHighlight>(
			0);

	public Month() {
	}

	public Month(int monthId, String monthLabel) {
		this.monthId = monthId;
		this.monthLabel = monthLabel;
	}

	public Month(int monthId, String monthLabel,
			Set<MonthlyFinancialHighlight> monthlyFinancialHighlights) {
		this.monthId = monthId;
		this.monthLabel = monthLabel;
		this.monthlyFinancialHighlights = monthlyFinancialHighlights;
	}

	@Id
	@Column(name = "month_id", unique = true, nullable = false)
	public int getMonthId() {
		return this.monthId;
	}

	public void setMonthId(int monthId) {
		this.monthId = monthId;
	}

	@Column(name = "month_label", nullable = false, length = 20)
	public String getMonthLabel() {
		return this.monthLabel;
	}

	public void setMonthLabel(String monthLabel) {
		this.monthLabel = monthLabel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "month")
	public Set<MonthlyFinancialHighlight> getMonthlyFinancialHighlights() {
		return this.monthlyFinancialHighlights;
	}

	public void setMonthlyFinancialHighlights(
			Set<MonthlyFinancialHighlight> monthlyFinancialHighlights) {
		this.monthlyFinancialHighlights = monthlyFinancialHighlights;
	}

}
