package com.nsmjsf.web.datamodels;

// Generated Mar 2, 2015 3:36:21 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MonthlyFinancialHighlight generated by hbm2java
 */
@Entity
@Table(name = "monthly_financial_highlight", catalog = "admin_nsmjsf")
public class MonthlyFinancialHighlight implements java.io.Serializable {

	private Integer monthlyFinancialHighlightId;
	private Announcement announcement;
	private FiscalYear fiscalYear;
	private Month month;
	private float monthlyFinancialHighlightNavPerShare;

	public MonthlyFinancialHighlight() {
	}

	public MonthlyFinancialHighlight(Announcement announcement,
			FiscalYear fiscalYear, Month month,
			float monthlyFinancialHighlightNavPerShare) {
		this.announcement = announcement;
		this.fiscalYear = fiscalYear;
		this.month = month;
		this.monthlyFinancialHighlightNavPerShare = monthlyFinancialHighlightNavPerShare;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "monthly_financial_highlight_id", unique = true, nullable = false)
	public Integer getMonthlyFinancialHighlightId() {
		return this.monthlyFinancialHighlightId;
	}

	public void setMonthlyFinancialHighlightId(
			Integer monthlyFinancialHighlightId) {
		this.monthlyFinancialHighlightId = monthlyFinancialHighlightId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "monthly_financial_highlight_announcement_id", nullable = false)
	public Announcement getAnnouncement() {
		return this.announcement;
	}

	public void setAnnouncement(Announcement announcement) {
		this.announcement = announcement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "monthly_financial_highlight_fiscal_year_id", nullable = false)
	public FiscalYear getFiscalYear() {
		return this.fiscalYear;
	}

	public void setFiscalYear(FiscalYear fiscalYear) {
		this.fiscalYear = fiscalYear;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "monthly_financial_highlight_month_id", nullable = false)
	public Month getMonth() {
		return this.month;
	}

	public void setMonth(Month month) {
		this.month = month;
	}

	@Column(name = "monthly_financial_highlight_nav_per_share", nullable = false, precision = 12, scale = 0)
	public float getMonthlyFinancialHighlightNavPerShare() {
		return this.monthlyFinancialHighlightNavPerShare;
	}

	public void setMonthlyFinancialHighlightNavPerShare(
			float monthlyFinancialHighlightNavPerShare) {
		this.monthlyFinancialHighlightNavPerShare = monthlyFinancialHighlightNavPerShare;
	}

}
