package com.nsmjsf.web.datamodels;

// Generated Feb 28, 2015 11:53:30 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PostImage generated by hbm2java
 */
@Entity
@Table(name = "post_image", catalog = "admin_nsmjsf")
public class PostImage implements java.io.Serializable {

	private Integer postImageId;
	private Post post;
	private String postImagePath;

	public PostImage() {
	}

	public PostImage(Post post, String postImagePath) {
		this.post = post;
		this.postImagePath = postImagePath;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "post_image_id", unique = true, nullable = false)
	public Integer getPostImageId() {
		return this.postImageId;
	}

	public void setPostImageId(Integer postImageId) {
		this.postImageId = postImageId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "post_image_post_id", nullable = false)
	public Post getPost() {
		return this.post;
	}

	public void setPost(Post post) {
		this.post = post;
	}

	@Column(name = "post_image_path", nullable = false, length = 65535)
	public String getPostImagePath() {
		return this.postImagePath;
	}

	public void setPostImagePath(String postImagePath) {
		this.postImagePath = postImagePath;
	}

}
