package com.nsmjsf.web.datamodels;

// Generated Feb 28, 2015 11:53:30 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Proxy generated by hbm2java
 */
@Entity
@Table(name = "proxy", catalog = "admin_nsmjsf")
public class Proxy implements java.io.Serializable {

	private ProxyId id;

	public Proxy() {
	}

	public Proxy(ProxyId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "proxyId", column = @Column(name = "proxy_id", nullable = false)),
			@AttributeOverride(name = "proxyIp", column = @Column(name = "proxy_ip", nullable = false)),
			@AttributeOverride(name = "proxySuccess", column = @Column(name = "proxy_success", nullable = false)),
			@AttributeOverride(name = "proxyFailed", column = @Column(name = "proxy_failed", nullable = false)),
			@AttributeOverride(name = "proxyPort", column = @Column(name = "proxy_port", nullable = false)) })
	public ProxyId getId() {
		return this.id;
	}

	public void setId(ProxyId id) {
		this.id = id;
	}

}
