package com.nsmjsf.web.datamodels;

// Generated Mar 14, 2015 9:52:11 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserBullion generated by hbm2java
 */
@Entity
@Table(name = "user_bullion", catalog = "admin_nsmjsf")
public class UserBullion implements java.io.Serializable {

	private Integer userBullionId;
	private User user;
	private BullionType bullionType;
	private Date userBullionBuyDate;
	private float userBullionBuyPrice;
	private String userBullionBuyUnitPrice;
	private int userBullionBuyUnits;
	private double userBullionTotalCost;
	private Set<UserBullionSales> userBullionSaleses = new HashSet<UserBullionSales>(
			0);

	public UserBullion() {
	}

	public UserBullion(User user, BullionType bullionType,
			Date userBullionBuyDate, float userBullionBuyPrice,
			String userBullionBuyUnitPrice, int userBullionBuyUnits,
			double userBullionTotalCost) {
		this.user = user;
		this.bullionType = bullionType;
		this.userBullionBuyDate = userBullionBuyDate;
		this.userBullionBuyPrice = userBullionBuyPrice;
		this.userBullionBuyUnitPrice = userBullionBuyUnitPrice;
		this.userBullionBuyUnits = userBullionBuyUnits;
		this.userBullionTotalCost = userBullionTotalCost;
	}

	public UserBullion(User user, BullionType bullionType,
			Date userBullionBuyDate, float userBullionBuyPrice,
			String userBullionBuyUnitPrice, int userBullionBuyUnits,
			double userBullionTotalCost,
			Set<UserBullionSales> userBullionSaleses) {
		this.user = user;
		this.bullionType = bullionType;
		this.userBullionBuyDate = userBullionBuyDate;
		this.userBullionBuyPrice = userBullionBuyPrice;
		this.userBullionBuyUnitPrice = userBullionBuyUnitPrice;
		this.userBullionBuyUnits = userBullionBuyUnits;
		this.userBullionTotalCost = userBullionTotalCost;
		this.userBullionSaleses = userBullionSaleses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_bullion_id", unique = true, nullable = false)
	public Integer getUserBullionId() {
		return this.userBullionId;
	}

	public void setUserBullionId(Integer userBullionId) {
		this.userBullionId = userBullionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_bullion_user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_bullion_type_id", nullable = false)
	public BullionType getBullionType() {
		return this.bullionType;
	}

	public void setBullionType(BullionType bullionType) {
		this.bullionType = bullionType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "user_bullion_buy_date", nullable = false, length = 0)
	public Date getUserBullionBuyDate() {
		return this.userBullionBuyDate;
	}

	public void setUserBullionBuyDate(Date userBullionBuyDate) {
		this.userBullionBuyDate = userBullionBuyDate;
	}

	@Column(name = "user_bullion_buy_price", nullable = false, precision = 12, scale = 0)
	public float getUserBullionBuyPrice() {
		return this.userBullionBuyPrice;
	}

	public void setUserBullionBuyPrice(float userBullionBuyPrice) {
		this.userBullionBuyPrice = userBullionBuyPrice;
	}

	@Column(name = "user_bullion_buy_unit_price", nullable = false)
	public String getUserBullionBuyUnitPrice() {
		return this.userBullionBuyUnitPrice;
	}

	public void setUserBullionBuyUnitPrice(String userBullionBuyUnitPrice) {
		this.userBullionBuyUnitPrice = userBullionBuyUnitPrice;
	}

	@Column(name = "user_bullion_buy_units", nullable = false)
	public int getUserBullionBuyUnits() {
		return this.userBullionBuyUnits;
	}

	public void setUserBullionBuyUnits(int userBullionBuyUnits) {
		this.userBullionBuyUnits = userBullionBuyUnits;
	}

	@Column(name = "user_bullion_total_cost", nullable = false, precision = 22, scale = 0)
	public double getUserBullionTotalCost() {
		return this.userBullionTotalCost;
	}

	public void setUserBullionTotalCost(double userBullionTotalCost) {
		this.userBullionTotalCost = userBullionTotalCost;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userBullion")
	public Set<UserBullionSales> getUserBullionSaleses() {
		return this.userBullionSaleses;
	}

	public void setUserBullionSaleses(Set<UserBullionSales> userBullionSaleses) {
		this.userBullionSaleses = userBullionSaleses;
	}

}
