package com.nsmjsf.web.datamodels;

// Generated Mar 14, 2015 9:52:11 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserWatchList generated by hbm2java
 */
@Entity
@Table(name = "user_watch_list", catalog = "admin_nsmjsf")
public class UserWatchList implements java.io.Serializable {

	private Integer userWatchListId;
	private User user;
	private String userWatchListLabel;
	private Date userWatchListDate;
	private Set<UserWatchListStock> userWatchListStocks = new HashSet<UserWatchListStock>(
			0);

	public UserWatchList() {
	}

	public UserWatchList(User user, String userWatchListLabel,
			Date userWatchListDate) {
		this.user = user;
		this.userWatchListLabel = userWatchListLabel;
		this.userWatchListDate = userWatchListDate;
	}

	public UserWatchList(User user, String userWatchListLabel,
			Date userWatchListDate, Set<UserWatchListStock> userWatchListStocks) {
		this.user = user;
		this.userWatchListLabel = userWatchListLabel;
		this.userWatchListDate = userWatchListDate;
		this.userWatchListStocks = userWatchListStocks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_watch_list_id", unique = true, nullable = false)
	public Integer getUserWatchListId() {
		return this.userWatchListId;
	}

	public void setUserWatchListId(Integer userWatchListId) {
		this.userWatchListId = userWatchListId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_watch_list_user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "user_watch_list_label", nullable = false)
	public String getUserWatchListLabel() {
		return this.userWatchListLabel;
	}

	public void setUserWatchListLabel(String userWatchListLabel) {
		this.userWatchListLabel = userWatchListLabel;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "user_watch_list_date", nullable = false, length = 0)
	public Date getUserWatchListDate() {
		return this.userWatchListDate;
	}

	public void setUserWatchListDate(Date userWatchListDate) {
		this.userWatchListDate = userWatchListDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userWatchList")
	public Set<UserWatchListStock> getUserWatchListStocks() {
		return this.userWatchListStocks;
	}

	public void setUserWatchListStocks(
			Set<UserWatchListStock> userWatchListStocks) {
		this.userWatchListStocks = userWatchListStocks;
	}

}
