package com.nsmjsf.web.datamodels;

// Generated Mar 14, 2015 9:52:11 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserType generated by hbm2java
 */
@Entity
@Table(name = "user_type", catalog = "admin_nsmjsf")
public class UserType implements java.io.Serializable {

	private Integer userTypeId;
	private String userTypeLabel;
	private Set<User> users = new HashSet<User>(0);

	public UserType() {
	}

	public UserType(String userTypeLabel) {
		this.userTypeLabel = userTypeLabel;
	}

	public UserType(String userTypeLabel, Set<User> users) {
		this.userTypeLabel = userTypeLabel;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_type_id", unique = true, nullable = false)
	public Integer getUserTypeId() {
		return this.userTypeId;
	}

	public void setUserTypeId(Integer userTypeId) {
		this.userTypeId = userTypeId;
	}

	@Column(name = "user_type_label", nullable = false)
	public String getUserTypeLabel() {
		return this.userTypeLabel;
	}

	public void setUserTypeLabel(String userTypeLabel) {
		this.userTypeLabel = userTypeLabel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userType")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
